### ISSUE TITLE
Editing robot files in the source tab causes massive lags

### ISSUE THREAD

**Issue by Double-A-92** [nokia/RED#319] opened 2019-07-22 07:47 UTC
**Situation**: I want to edit a relatively small robot file (50 lines) in a big test project (100s of files and keywords).

**Problem**: Editing the file in the 'robot' tab instead of 'Test Cases' tab is almost impossible. Any small action (selecting something, moving the cursor, starting to type, pasting code,...) regularly causes a 5-10 second long stutter.

**System**: RED_0.8.13.20190718102048-win32.win32.x86_64 on Windows 7

**Comment by michalanglart** [comment] 2019-07-22 12:53
Hi,

first of all: were you experiencing this problem in older versions or does it started to appear after updating to 0.8.13?

It would be great to have more details or ideally some exemplary project on which you're able to reproduce the problem. With the description above it's hard to say anything.

Please have a look into the discussion under #301 - in this case sluggishness was fixed by properly setting up the project.

**Comment by michalanglart** [comment] 2019-11-14 13:50
No response since opening; no other user reported similar issue in the meantime, so I'm closing this one as we are not reproducing this issue.

**Closed by michalanglart** 2019-11-14 13:50 UTC

**Comment by Double-A-92** [comment] 2019-11-14 13:55
Sorry for not responding. It was really because the project was not properly set up as a real RED project.

**Comment by michalanglart** [comment] 2019-11-14 13:56
Ok, so it is working ok now?

**Comment by Double-A-92** [comment] 2019-11-14 14:16
Yes seems to work properly. The only problem I had was with the paths in the red.xml because they can't be relative and it keeps adding some python path from my %appdata% to it. But that's another issue I guess.

**Comment by michalanglart** [comment] 2019-11-14 14:23
Yes, that's another issue for sure. Feel free to open it if you wish!
