### ISSUE TITLE
Unhandled event loop exception

### ISSUE THREAD

**Issue by spirentitestdevter** [nokia/RED#309] opened 2019-06-04 02:50 UTC
Hi,

I'm developing a target platform base on eclipse 4.11, I included RED v0.8.11 using target file and used maven to build a product. I always get error when open a robot file source tab. I can not do every thing because this issue. Could you take a look on it ?

Thanks,
Nghia

Here is error log:
*eclipse.buildId=unknown
java.version=11.0.3
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.eclipse.ui
Error
Tue Jun 04 09:39:28 ICT 2019
Unhandled event loop exception

java.lang.ClassCastException: class org.eclipse.jface.action.SubContributionItem cannot be cast to class org.eclipse.ui.texteditor.StatusLineContributionItem (org.eclipse.jface.action.SubContributionItem is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @587c5c1; org.eclipse.ui.texteditor.StatusLineContributionItem is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1447bef2)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.source.SuiteSourceEditor.updateLineLocationStatusBar(SuiteSourceEditor.java:207)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.source.SuiteSourceEditor.lambda$2(SuiteSourceEditor.java:195)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:101)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1064)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.eclipse.swt.custom.StyledText.setCaretOffset(StyledText.java:8795)
	at org.eclipse.swt.custom.StyledText.doMouseLocationChange(StyledText.java:2853)
	at org.eclipse.swt.custom.StyledText.handleMouseDown(StyledText.java:6162)
	at org.eclipse.swt.custom.StyledText.lambda$1(StyledText.java:5789)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:566)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at com.fnfr.svt.rcp.Application.runWorkbench(Application.java:231)
	at com.fnfr.svt.rcp.Application.start(Application.java:190)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:661)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1476)

*

**Comment by michalanglart** [comment] 2019-06-04 14:01
Hi,

I'm unable to reproduce your issue. How is your target platform configured? What features does it include?

Are you aware of any plugins which somehow would contribute to action bar? In the definition of editor: https://github.com/nokia/RED/blob/aa36f057d37e52d7c1498637f46af21e4a7e6026/src/Eclipse-IDE/org.robotframework.ide.eclipse.main.plugin/plugin.xml#L341 we add action bars contributor which itself is defined here: https://github.com/nokia/RED/blob/master/src/Eclipse-IDE/org.robotframework.ide.eclipse.main.plugin/src/org/robotframework/ide/eclipse/main/plugin/tableeditor/RobotFormEditorActionBarContributor.java

As you can see in the source this contributor adds `StatusLineContributionItem` under `ITextEditorActionConstants.STATUS_CATEGORY_INPUT_POSITION` category. 

Then `SuiteSourceEditor` attaches a listener on a caret position and here: https://github.com/nokia/RED/blob/aa36f057d37e52d7c1498637f46af21e4a7e6026/src/Eclipse-IDE/org.robotframework.ide.eclipse.main.plugin/src/org/robotframework/ide/eclipse/main/plugin/tableeditor/source/SuiteSourceEditor.java#L207 it looks for the item in order to update position. It expects to be of type `StatusLineContributionItem` since the contributor registered this item under the same category.

Overall this mechanism is responsible for displaying and updating the element marked with red on screenshot:
![source_position](https://user-images.githubusercontent.com/14932410/58884852-76c69480-86e1-11e9-93fc-3d49d4947d37.png)

Do you have other plugins possibly somehow altering the items contributed to status line when Robot editor is open?

**Comment by michalanglart** [comment] 2019-10-24 13:31
Closing due to no answers from reporter + no one else run into this issue. RED 0.9.0 is based on eclipse 4.13 instead of 4.9, so maybe this is also fixed (if this was RED issue)

**Comment by spirentitestdevter** [comment] 2020-06-25 03:54
Sorry for my late response. We imported RED source codes to my project and added workaround for RED v0.8.11. Now We upgrade the Eclipse and upgrade RED and get error again, we could have to add source codes again. We hope that you can fix it in next release to avoid our effort. I'm very appreciate your help.

**Comment by michalanglart** [comment] 2020-07-24 11:21
Fixed this exception in 0.9.5

**Closed by michalanglart** 2020-07-24 11:21 UTC
Labels: bug
