### ISSUE TITLE
Documentation not working correctly when keywords and testcases are folded

### ISSUE THREAD

**Issue by mtoskamp** [nokia/RED#357] opened 2019-12-11 11:14 UTC
When folding keywords and testcases in RED and then using show documentation in a keyword or testcase, underneath the folded one, you somehow get the documentation of what is on the actual line of the folded item.

So instead of ignoring all folded lines it will remain giving me documentation about what would be on the exact line if everything was shown (unfolded).
Underneath screenshot is an example of the problem. The red bordered testcase is what I get the documentation for, while I am trying to show the documentation of the green bordered keyword, which is in another testcase.

![image](https://user-images.githubusercontent.com/58772827/70616434-b6c97f80-1c0e-11ea-9cb0-1e6928a6da56.png)

When unfolding above testcase the functionality is working correctly again.

**Comment by michalanglart** [comment] 2019-12-11 13:57
Hi,

interesting finding, thanks for that! I can confirm this is reproducible even on very simple cases with RED 0.9.1

**Comment by michalanglart** [comment] 2019-12-11 14:19
I've checked that ant looks to be fixed trivially. The problem was that we were getting the offset of caret inside the widget and this was used to find element the document and then in parsed model but when something is folded this offset is different than the offsets in undelying document. This creates a mismatch and results in displaying documentations different than those under caret.

It requires a small fix in single line of code, so we'll fix that for next version which we want to release next week.

**Comment by mtoskamp** [comment] 2019-12-11 14:37
> It requires a small fix in single line of code, so we'll fix that for next version which we want to release next week.

@michalanglart awesome to see you guys are so pro actively working on the editor and even solving problems, even though they might have low priority ;),  in such a short notice. I was already fond of the editor, but loving it even more now!

**Comment by michalanglart** [comment] 2019-12-11 14:49
@mtoskamp thanks, glad to hear that!

This one had a luck, it usually takes more time to fix bugs :)

**Comment by michalanglart** [comment] 2019-12-17 15:10
Fix is released in 0.9.2

**Closed by michalanglart** 2019-12-17 15:10 UTC
Labels: bug
