### ISSUE TITLE
Unable to communicate with XML-RPC server while reloading a python referenced library for robotframework

### ISSUE THREAD

**Issue by oussos** [nokia/RED#397] opened 2020-10-24 07:20 UTC
Hello,

The error "Unable to communicate with XML-RPC server" displayed in the below screenshot is occured while I try to reload a python file for robot referenced libraries in Eclipse:
![image](https://user-images.githubusercontent.com/65712264/97070304-36660000-15cf-11eb-98c6-0e02bb436778.png)

My installation is:

- Eclipse Platform 4.17.0.v20200910-1200
- RED - Robot Editor 0.9.5.202007240959
- PyDev for Eclipse 8.0.0.202009061309
- Python 3.8

**Comment by michalanglart** [comment] 2020-10-27 07:42
Hi,

can you please give us content of `.log` file from `metadata` directory in you workspace?

**Comment by oussos** [comment] 2020-10-27 22:22
Hi michalanglart,

Thank you for your reply!

I didn't get how to attach the .log file.

I got in .log file the below Exceptions:
!ENTRY org.eclipse.core.jobs 4 2 2020-10-27 22:10:56.317
!MESSAGE An internal error occurred during: "Validating".
!STACK 0
org.rf.ide.core.environment.IRuntimeEnvironment$RuntimeEnvironmentException: Unable to communicate with XML-RPC server
	at org.rf.ide.core.environment.RobotCommandRpcExecutor.getStandardLibrariesNames(RobotCommandRpcExecutor.java:170)
	at org.rf.ide.core.environment.RobotRuntimeEnvironment.getStandardLibrariesNames(RobotRuntimeEnvironment.java:136)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotProject.getStandardLibraries(RobotProject.java:117)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotProject.getLibrarySpecificationsStream(RobotProject.java:180)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotProject.getLibrarySpecifications(RobotProject.java:193)
	at org.robotframework.ide.eclipse.main.plugin.project.build.validation.ValidationContext.collectLibraries(ValidationContext.java:86)
	at org.robotframework.ide.eclipse.main.plugin.project.build.validation.ValidationContext.<init>(ValidationContext.java:72)
	at org.robotframework.ide.eclipse.main.plugin.project.build.RobotArtifactsValidator.runValidation(RobotArtifactsValidator.java:159)
	at org.robotframework.ide.eclipse.main.plugin.project.build.RobotArtifactsValidator.access$3(RobotArtifactsValidator.java:146)
	at org.robotframework.ide.eclipse.main.plugin.project.build.RobotArtifactsValidator$4.run(RobotArtifactsValidator.java:141)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.xmlrpc.XmlRpcException: Failed to create input stream: Read timed out
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.getInputStream(XmlRpcSunHttpTransport.java:99)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:152)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:137)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:126)
	at org.rf.ide.core.environment.RobotCommandRpcExecutor.callRpcFunction(RobotCommandRpcExecutor.java:412)
	at org.rf.ide.core.environment.RobotCommandRpcExecutor.getStandardLibrariesNames(RobotCommandRpcExecutor.java:164)
	... 10 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:284)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:310)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:351)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:802)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:937)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:245)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:285)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:344)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1610)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.getInputStream(XmlRpcSunHttpTransport.java:92)
	... 19 more

**Comment by oussos** [comment] 2020-10-27 22:23
Hi michalanglart,

Thank you for your reply!

I didn't get how to attach the .log file.

I got in .log file the below Exceptions:

!ENTRY org.eclipse.core.jobs 4 2 2020-10-27 22:10:56.317
!MESSAGE An internal error occurred during: "Validating".
!STACK 0
org.rf.ide.core.environment.IRuntimeEnvironment$RuntimeEnvironmentException: Unable to communicate with XML-RPC server
	at org.rf.ide.core.environment.RobotCommandRpcExecutor.getStandardLibrariesNames(RobotCommandRpcExecutor.java:170)
	at org.rf.ide.core.environment.RobotRuntimeEnvironment.getStandardLibrariesNames(RobotRuntimeEnvironment.java:136)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotProject.getStandardLibraries(RobotProject.java:117)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotProject.getLibrarySpecificationsStream(RobotProject.java:180)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotProject.getLibrarySpecifications(RobotProject.java:193)
	at org.robotframework.ide.eclipse.main.plugin.project.build.validation.ValidationContext.collectLibraries(ValidationContext.java:86)
	at org.robotframework.ide.eclipse.main.plugin.project.build.validation.ValidationContext.<init>(ValidationContext.java:72)
	at org.robotframework.ide.eclipse.main.plugin.project.build.RobotArtifactsValidator.runValidation(RobotArtifactsValidator.java:159)
	at org.robotframework.ide.eclipse.main.plugin.project.build.RobotArtifactsValidator.access$3(RobotArtifactsValidator.java:146)
	at org.robotframework.ide.eclipse.main.plugin.project.build.RobotArtifactsValidator$4.run(RobotArtifactsValidator.java:141)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.apache.xmlrpc.XmlRpcException: Failed to create input stream: Read timed out
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.getInputStream(XmlRpcSunHttpTransport.java:99)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:152)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:137)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:126)
	at org.rf.ide.core.environment.RobotCommandRpcExecutor.callRpcFunction(RobotCommandRpcExecutor.java:412)
	at org.rf.ide.core.environment.RobotCommandRpcExecutor.getStandardLibrariesNames(RobotCommandRpcExecutor.java:164)
	... 10 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:284)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:310)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:351)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:802)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:937)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:245)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:285)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:344)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1610)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.getInputStream(XmlRpcSunHttpTransport.java:92)
	... 19 more

**Comment by michalanglart** [comment] 2020-10-28 07:02
Ok,

nothing obvious here. Do you have any special network configuration? Blocked ports, proxies, firewalls?

Please have a look here: https://nokia.github.io/RED/help/user_guide/diagnostics.html and try to show the console of session server (paragraph 1) or alternatively run the session server manually and then start RED so that it would connect to it (paragraph 2). Please give us all the output from server console.

**Comment by oussos** [comment] 2020-10-29 18:32
I used the steps of the first paragraph and the output of the server console is attached below:
[server console.txt](https://github.com/nokia/RED/files/5460517/server.console.txt)

**Comment by oussos** [comment] 2020-10-29 18:36
> Do you have any special network configuration? Blocked ports, proxies, firewalls?

I don't have any special network, I wok with my laptop just for personal use.

**Comment by michalanglart** [comment] 2020-10-29 19:43
Interesting case, we need to try to reproduce it on our side.

Can you please check if it works once you would disable preference: `Preferences->Robot Framework->Libraries->Generate python libraries libdocs in separate process`?

**Comment by michalanglart** [comment] 2020-10-29 19:46
Additionally - this is your custom library, right? `D:\Selenium\Search_elements_In_Websites\Search_HTML_CSS_Elements\ExternalKeywords\get_css_value.py`

What it does in library constructor? Is there anything specific other than simply setting object fields? Are you able to generate library specification file using `robot.libdoc` (see https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#library-documentation-tool-libdoc)?

**Comment by oussos** [comment] 2020-10-30 20:19
> Can you please check if it works once you would disable preference: Preferences->Robot Framework->Libraries->Generate python libraries libdocs in separate process?

Yes, now it works 
Thank you !

**Comment by oussos** [comment] 2020-10-30 21:18
> Additionally - this is your custom library, right? D:\Selenium\Search_elements_In_Websites\Search_HTML_CSS_Elements\ExternalKeywords\get_css_value.py

Yes, it is my custom library attached below

[get_css_value.zip](https://github.com/nokia/RED/files/5467703/get_css_value.zip)

**Comment by michalanglart** [comment] 2020-11-02 21:20
Ok,

the problem is unfortunately with your library. Please try to generate the library documentation for your library by using `robot.libdoc` tool - for example:

`
python -m robot.libdoc path/to/get_css_value.py path/to/get_css_value_doc.html
`

The libdoc tool basically imports your file which means that it will execute all the code at global level and on global level you're creating a web driver for chrome, which opens the browser. And this is done just for the purpose of generating a documentation! This is what RED does and that's why it has a problem.

You should rather implement your library as a class with methods as keywords. In such case libdoc will of course still run the global code (an it will also run the code in __init__ constructor of your class!) but hopefully you would be able to write in a way that there would be no need to run chrome browser just for the sake of the file being imported and documentation being generated by libdoc.

**Comment by michalanglart** [comment] 2020-11-02 21:24
Be aware that if you would implement a library this way:
```
while True:
    pass
def keyword():
    return 1
```

or:
```
class MyLibrary(object):
    def __init__(self):
        while(True):
            pass
    def keyword(self):
        return 1
```

then trying to generate docu with `robot.libdoc` would hang it forever and also RED would hang its server for RED-robot integration.

**Comment by oussos** [comment] 2020-11-10 05:43
Hello,

C:\Users\pc>python -m robot.libdoc D:/Selenium/Search_elements_In_Websites/Search_HTML_CSS_Elements/ExternalKeywords/get_css_value.py D:/Selenium/Search_elements_In_Websites/Search_HTML_CSS_Elements/ExternalKeywords/get_css_value_doc.html

DevTools listening on ws://127.0.0.1:49605/devtools/browser/2ccabc34-5376-4805-8e2f-3e42135308b5
D:\Selenium\Search_elements_In_Websites\Search_HTML_CSS_Elements\ExternalKeywords\get_css_value_doc.html

C:\Users\pc>

I have attached below the HTML generated file:
[get_css_value_doc.zip](https://github.com/nokia/RED/files/5515092/get_css_value_doc.zip)

**Comment by michalanglart** [comment] 2020-11-16 22:53
Hi,

the output above just confirms what I've written above. Libdoc would run your browser for the sake of creating a documentation. Why would need browser just to be able to generate some html documentation of your library? It is not only not needed but as you can see it also messes with RED session server.

**Comment by oussos** [comment] 2020-11-17 20:32
Hello,

I implemented the above python library this way:
```
while True:
    pass
def keyword():
    return 1
```
But, in this case, the problem of communication with XML-RPC server was occurred again.

> It is not only not needed but as you can see it also messes with RED session server.

Do you mean by RED session server the XML-RPC server?
If yes, I notice that it messes with RED session server when I disable this preference: `Preferences->Robot Framework->Libraries->Generate python libraries libdocs in separate process`

**Comment by michalanglart** [comment] 2020-11-18 07:32
Hi,

> I implemented the above python library this way

Well, I'm confused - I gave this code snippet telling that you "should be aware" that the python code in the top-level is executed when `robot.libdoc` generates documentation. In this code snippet I've placed infinite loop to demonstrate that `robot.libdoc` will not generate the documentation but it will hang infinitely until one would kill the process. My idea was to show you that you should be aware of that when writing library and to avoid that - in your case you're opening browser in top-level code so `robot.libdoc` will do that while it should just generate the documentation.

**Comment by oussos** [comment] 2020-11-19 05:05
Hi,

Thank you @michalanglart for your clarification.

In summary then, to avoid the issue, I should mainly check two things:

1. Disable preference: `Preferences->Robot Framework->Libraries->Generate python libraries libdocs in separate process`
2. Not implementing the library the way described in the [comment12](https://github.com/nokia/RED/issues/397#issuecomment-720732783) to avoid hanging its server for RED-robot integration

Is it right?

**Comment by michalanglart** [comment] 2020-11-19 07:40
Well preference may be helpful in some cases (like yours) but it wouldn't help in case of "hanging" library like the one from my comment.

In Object Oriented Programming we have this coding "best practice" telling that objects constructors should not have any code other than simply assigning parameters to object fields (see https://www.yegor256.com/2015/05/07/ctors-must-be-code-free.html ).

I think that this rule may be extended and applied for writing "clean" Robot libraries: do not put any non-trivial code/computations inside the library constructor or in the top-level scope. This would mean that declaring and assigning fields/globals is fine, initializing fields/globals from already known values is fine, but performing complex task like doing I/O or opening the browser is big no-no.

If you open the browser at top-level (as you do in your library) then this browser would open just because someone would do:
```
import get_css_value
```
the same come with constructors but in the moment of object creation, not when importing the module.

**Comment by NikitaOstr** [comment] 2020-11-22 17:40
Hi
I have the same issue with XML-RPC but in my case it's just internal error while 'Validating'
![red1](https://user-images.githubusercontent.com/45942078/99910960-e8413b00-2cf9-11eb-8786-a17b96baae94.JPG)

After that RED stops working normally, every minute pop up with the error.
Together with it I found that Robot Framework is not recognized in red.xml eventually
![red2](https://user-images.githubusercontent.com/45942078/99911000-2a6a7c80-2cfa-11eb-86c2-1f2ead0b9edc.JPG)

I even don't know where to search for resolving the issue. Will be appreciated for any help!)

PS: I downloaded all-in-one solution from https://github.com/nokia/RED/releases/download/0.9.5/RED_0.9.5.20200724101746-win32.win32.x86_64.zip

**Comment by oussos** [comment] 2020-11-22 21:01
> If you open the browser at top-level (as you do in your library) then this browser would open just because someone would do:
> `import get_css_value`
> the same come with constructors but in the moment of object creation, not when importing the module.

Thank you @michalanglart for your notice.
So, to avoid opening browser at top-level (like making computations inside the library constructor), I remove `Open_website` **method** inside my library and I use instead the `Open Browser` **keyword** within my robot framework code snippet.
Could you confirm the above alternative ?

**Comment by michalanglart** [comment] 2020-12-11 11:32
Yes - simply avoid any complicated stuff in the library on the top-level in code or in the library constructor, because robot.libdoc would execute this when generating documentation

**Closed as completed** 2020-12-19 15:36 UTC

**Comment by oussos** [comment] 2020-12-19 15:37
Thank you @michalanglart. It's cleared now for me.
