### ISSUE TITLE
Chinses chars output in Eclipse console will be wrong.

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#214] opened 2018-05-28 08:30 UTC
I have:
1  a .robot file with Chinese char
2  a testcase name with Chinese char
3  a log output code with Chinese char

In robot message view, all above shows correct.

In eclipse console view, it will be wrong.
If I set the charset in launch config to UTF8, the chinese log will be display well. but filename and testcase name can not display.
If I set the lanuch config charset to GBK, filename and testcase name can display good, but chinese log can not display.

**Comment by Pantyhose-S** [comment] 2018-05-28 08:34
err, I mean
1 a .robot file with Chinese char
   example:  中文.robot

3 a log output code with Chinese char
   example:  log  中文日志

**Comment by Pantyhose-S** [comment] 2018-05-28 08:37
by the way, I am using a Chinese version windows 7, it's default charset is GBK

**Comment by michalanglart** [comment] 2018-05-28 08:39
Hi,

what are your RED, python & RF versions?

Please have a look to this issue: #160 

If you're using python 2.7 then you will need to wait for RF 3.1 because up till current version we were unable to enforce utf encoding of output streams and Robot was wrongly using some different encodings. This was raised by me at RF tracker: https://github.com/robotframework/robotframework/issues/2750 and just recently solved.

**Comment by Pantyhose-S** [comment] 2018-08-09 15:17
In python 3.6 I can make it all right, in 2.7 I did not try it.

**Comment by KrzysztofJozefowicz** [comment] 2018-08-10 09:27
Thanks for feedback, I will leave this issue open for some time, if you would have a time to check it with newest RF and Pyt 2.7 we would be grateful.

**Comment by kenifanying** [comment] 2018-09-18 05:45
I can confirm this bug has been fixed with Robot Framework 3.1a1 (Python 2.7.15 on win32)

![snipaste_20180918_134505](https://user-images.githubusercontent.com/4479181/45666766-112d7a80-bb49-11e8-8c7e-41feab54ffc1.png)

**Comment by michalanglart** [comment] 2018-09-18 07:15
Great, glad to hear!

**Closed by michalanglart** 2018-09-18 07:15 UTC
Labels: help wanted
