### ISSUE TITLE
argument file starting from home directory is not working

### ISSUE THREAD

**Issue by p74** [nokia/RED#208] opened 2018-05-18 09:40 UTC
`- A ~/robotframeworktest/argumentfiles/bla.txt`

i need to set whole path

greetings Ruud

**Comment by michalanglart** [comment] 2018-05-18 10:38
Hi,

in which place are you trying try to use this path?

**Comment by p74** [comment] 2018-05-18 10:41
Hi.

In "Run Configurations" screen , tab "Robot" field,  "Arguments"

2018-05-18 12:38 GMT+02:00 michalanglart <notifications@github.com>:

**Comment by adam-wypych** [comment] 2018-06-01 07:31
what is your operating system?

**Comment by p74** [comment] 2018-06-01 20:17
Linux Ubuntu 17.10

Op vr 1 jun. 2018 09:31 schreef adam-wypych <notifications@github.com>:

**Comment by adam-wypych** [comment] 2018-06-01 20:51
I think the problem is because `~` is resolved by shell and with the python is even more complicated (just see: https://stackoverflow.com/questions/11587343/difference-between-home-and-tilde ). Therefore please try to use '$HOME' instead of tilde.

**Comment by modrz** [comment] 2018-06-14 12:53
Since RED 0.8.5 Eclipse string substitution variables are supported in run configuration text fields.
On linux you can replace tilde by:
`-A ${env_var:HOME}/robotframeworktest/argumentfiles/bla.txt`

**Comment by adam-wypych** [comment] 2018-06-14 13:02
@p74 could you try suggestion from @modrz https://github.com/nokia/RED/issues/208#issuecomment-397284164

**Comment by KrzysztofJozefowicz** [comment] 2018-08-08 07:51
released in 0.8.7

**Closed by KrzysztofJozefowicz** 2018-08-08 07:51 UTC
