### ISSUE TITLE
[BUG?]red.xml will be change when rename a file

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#112] opened 2017-06-07 14:07 UTC
When I rename a file in my project (filename include Chinese chars)
the red.xml will be wrote broken, the library section changed into the filename.

Maybe it is a bug?

**Comment by KrzysztofJozefowicz** [comment] 2017-06-07 18:55
Thanks for reporting. Indeed,something is wrong when unicode file is renamed while in red.xml referenced library entry is present,  We will look into it.

**Comment by KrzysztofJozefowicz** [comment] 2017-06-12 12:40
Rename of file,file move or project rename causes the same outcome - referenced libraries part is edited.
It is not caused by unicode/chinees/special characters, it was introduced in "Project Rename" functionality.
Either we will fix it in next release (rewriting) or we will roll back this feature.

**Comment by KrzysztofJozefowicz** [comment] 2017-06-29 10:10
Project Rename feature was disabled in 0.7.9

**Comment by KrzysztofJozefowicz** [comment] 2017-11-27 11:08
released in 0.8.1

**Closed** 2017-11-27 11:29 UTC
Labels: bug
