### ISSUE TITLE
Excessive project rebuilts in Eclipse

### ISSUE THREAD

**Issue by mcpat** [nokia/RED#233] opened 2018-07-02 13:54 UTC
The current version seems to have awkward dependencies/requirements on the Eclipse workspace:

1. Whenever a Robot run is triggered (regardless whether through Run... or Debug...) all open projects in the workspace will be rebuilt prior the execution of robot.
2. Whenever RED preferences (Window -> Preferences -> ...) are edited or changed all open projects in the workspace will be rebuilt.

**Comment by modrz** [comment] 2018-07-03 09:18
Is it clean RED product/Eclipse + RED feature installation or you have other plugins installed?

**Comment by mcpat** [comment] 2018-07-03 14:38
It's a Eclipse CDT with RED.

**Comment by modrz** [comment] 2018-07-04 09:54
Unfortunately I can't reproduce it.
Can you provide more details?
Have you upgraded older version to current one?
You may try to use **-clean** option in eclipse.ini

**Comment by KrzysztofJozefowicz** [comment] 2018-08-08 07:55
@mcpat has anything changed with new version 0.8.7? Have you tried to replicate your case with clean RED binnary?

**Comment by michalanglart** [comment] 2018-10-09 10:59
It seems nothing more can be done on our side as we can't reproduce it with the available information. Closing

**Closed by michalanglart** 2018-10-09 10:59 UTC
Labels: help wanted
