### ISSUE TITLE
Failed to create the part's controls 'Revalidating model' has encountered a problem.

### ISSUE THREAD

**Issue by paul-divine** [nokia/RED#31] opened 2016-08-03 05:44 UTC
Eclipse IDE for Java Developers
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

Robot Framework 3.0 (Python 2.7.6 on win32)
RED - Robot Editor version 0.6.5

After the installation of the new eclipse version and the new Robot framework editor
![red_failto_create_part_s_control](https://cloud.githubusercontent.com/assets/20796737/17332078/cf3dd668-58cd-11e6-8594-5fceaa9a9f4f.png)
![red_failto_create_part_s_control](https://cloud.githubusercontent.com/assets/20796737/17355021/d9b254d6-594d-11e6-8e59-4a2fbc3e959c.png)

 RED

**Comment by adam-wypych** [comment] 2016-08-03 05:51
Hi,

Could You attach `.log` file content or add it to `gist` to check.

Thanks in advance.

BR,
-Adam.

**Comment by paul-divine** [comment] 2016-08-03 06:01
Here is the log file
[log.txt](https://github.com/nokia/RED/files/398747/log.txt)

**Comment by paul-divine** [comment] 2016-08-03 06:02
Sorry I close the issue by error

**Comment by adam-wypych** [comment] 2016-08-03 06:05
Hi,

For be ensure do You use Java 7 version?

BR,
-Adam.

**Comment by paul-divine** [comment] 2016-08-03 06:07
yes

**Comment by adam-wypych** [comment] 2016-08-03 06:10
Ok, so I know what is issue. We for mistake used Java API from Java 8, where class `java.util.List` has method `sort` (see: https://docs.oracle.com/javase/8/docs/api/java/util/List.html) in Java 7 the method is not available. Therefore if You can please update Java version to 1,8 as workaround or wait for new upcoming release hope this week.

**Comment by paul-divine** [comment] 2016-08-03 06:12
Hi Adam,
I cannot update to Java version 1.8 so I will wait.
Thank you very much.
Paul

**Comment by adam-wypych** [comment] 2016-08-03 06:40
Fixed will be available in next release.

**Comment by KrzysztofJozefowicz** [comment] 2016-09-14 11:38
released in 0.7.0

**Closed by KrzysztofJozefowicz** 2016-09-14 11:38 UTC
Labels: bug

**Comment by thangaroja** [comment] 2017-03-21 21:43
I have the same issue. I use RED editor and my current Java version is 1.8. Can someone suggest me on this?

**Comment by michalanglart** [comment] 2017-03-22 08:00
Hi,

What is the message of an error? Also take a look into .log file located in .metadata directory inside your workspace and attach it, or copy errors which are logged in this file (try to find the exact one, since this file is not cleared, so you may find errors logged months ago).

**Comment by thangaroja** [comment] 2017-03-22 08:35
I'm getting various logs like the below,
org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTException: Widget is disposed)
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
Caused by: org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:354)
	at org.eclipse.swt.widgets.Control.setFocus(Control.java:3445)
	at org.eclipse.jdt.internal.ui.text.java.hover.AbstractAnnotationHover$AnnotationInformationControl.setFocus(AbstractAnnotationHover.java:209)
	at org.eclipse.jface.text.AbstractInformationControlManager.showInformationControl(AbstractInformationControlManager.java:1289)
	at org.eclipse.jface.internal.text.StickyHoverManager.showInformationControl(StickyHoverManager.java:264)
	at org.eclipse.jface.internal.text.InformationControlReplacer.showInformationControl(InformationControlReplacer.java:161)
	at org.eclipse.jface.text.AbstractInformationControlManager.internalShowInformationControl(AbstractInformationControlManager.java:1177)
	at org.eclipse.jface.text.AbstractInformationControlManager.presentInformation(AbstractInformationControlManager.java:1163)
	at org.eclipse.jface.text.AbstractInformationControlManager.setInformation(AbstractInformationControlManager.java:428)
	at org.eclipse.jface.internal.text.InformationControlReplacer.computeInformation(InformationControlReplacer.java:113)
	at org.eclipse.jface.text.AbstractInformationControlManager.doShowInformation(AbstractInformationControlManager.java:1144)
	at org.eclipse.jface.text.AbstractInformationControlManager.showInformation(AbstractInformationControlManager.java:1134)
	at org.eclipse.jface.internal.text.InformationControlReplacer.replaceInformationControl(InformationControlReplacer.java:100)
	at org.eclipse.jface.text.AbstractInformationControlManager.replaceInformationControl(AbstractInformationControlManager.java:1311)
	at org.eclipse.jface.text.AbstractHoverInformationControlManager.replaceInformationControl(AbstractHoverInformationControlManager.java:801)
	at org.eclipse.jface.text.TextViewerHoverManager.replaceInformationControl(TextViewerHoverManager.java:303)
	at org.eclipse.jface.text.AbstractHoverInformationControlManager$Closer$2.run(AbstractHoverInformationControlManager.java:301)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	... 23 more

**Comment by thangaroja** [comment] 2017-03-22 08:36
One more is something like this,
Message:   No repository found at jar:file:/C:/Java/RED-master%20(2).zip!/.
eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

**Comment by thangaroja** [comment] 2017-03-22 08:38
Im getting something like below,

Message :  No repository found at jar:file:/C:/Java/RED-master%20(2).zip!/.

eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

**Comment by thangaroja** [comment] 2017-03-22 08:49
This issue close the eclipse always.
Message: An internal error occurred during: "Revalidating model".

eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

**Comment by thangaroja** [comment] 2017-03-22 09:00
Is this the right way if i can delete all the folders and files under myJavaworkspace/.metadata/.plugins/?

**Comment by michalanglart** [comment] 2017-03-22 09:10
.metadata folder contains many settings which are stored by features working in your eclipse; If it causes some problems it would be probably better to create new workspace and import your projects inside it. See for example this question: http://stackoverflow.com/questions/7279992/should-i-regularly-delete-the-metadata-folder-from-the-eclipse-workspace-what

As to the error: can you attach whole .log file?

**Comment by thangaroja** [comment] 2017-03-22 09:59
Im unable to attach the log file here. (.log file). Tried with multiple file types. Can i have your email Id or is there any possibility attaching anywhere else?

**Comment by michalanglart** [comment] 2017-03-22 10:19
https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

Probably you may need to change file extension to .txt

**Comment by thangaroja** [comment] 2017-03-22 10:26
Hi,

Please find attached eclipse log file.

Regards,
Thanga Roja
Automation Test Specialist
+91 9159768557

**Comment by michalanglart** [comment] 2017-03-22 10:31
Your eclipse run out of memory. You may change it in .ini file:
https://github.com/nokia/RED/blob/master/red_help/user_guide/eclipse_memory.html.md

You have to restart eclipse if new settings has to be taken into account

**Comment by thangaroja** [comment] 2017-03-23 03:55
Yes you are right. I followed the below steps and made it clear. It works fastly without any validation now. Thanks a lot for your patience and the help done.

1) Increased Java Heap Size : https://www.youtube.com/watch?v=WYtH5yJRz5s
           a) Heap size provided: -Xms512m -Xmx1152m -XX:MaxPermSize=256m -XX:MaxNewSize=256m
           b) Deleted duplicate JRE files(older version).
2) Restarted the system after the settings done.
