### ISSUE TITLE
Teardown will not be run by "stop" button.

### ISSUE THREAD

**Issue by Pantyhose-S** [nokia/RED#192] opened 2018-03-06 02:16 UTC
I RIDE， when I stop the script, the teardown will be run, this is useful.
But in RED, when I click stop button, teardown will not run. So I need to clean the test env by myself.

Also, is there a "auto stop script when keyword fails" option?

**Comment by michalanglart** [comment] 2018-03-06 08:34
Hi,

According to user guide: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#handling-teardowns teardown are executed when tests are asked to terminate gently by e.g. sending SIGTERM or SIGINT singal under linux. So basically this is the same issue you've already raised in #170. Unfortunately we haven't done any progress in this topic yet.

As to the second question: I don't know exactly what this option is doing in RIDE under the hood but I assume that it may simply add `--exitonfailure` argument to command line. There are no such button in RED you can however add this argument on your own in `Additional Robot Framework arguments` field of Run Configuration (http://nokia.github.io/RED/help/user_guide/launching/local_launch.html). You can also edit preferences as described here: http://nokia.github.io/RED/help/user_guide/launching/launch_prefs.html in `Default launch configurations` paragraph, so that this argument will always be added to every newly created launch configuration.

**Comment by Pantyhose-S** [comment] 2018-03-07 14:59
Err, what I want is, when a keyword fails, auto toggle a "break point" on it, and I will see what happened.
I do not know what keyword will fail, so if any keyword fails, the script will pause.

**Comment by michalanglart** [comment] 2018-03-07 15:13
Ok, now I understand. This is basically this one: #77 right?

It's not implemented yet, however it should be fairly straightforward to implement it after we've made debugger refactoring last year.

**Comment by michalanglart** [comment] 2018-05-18 10:47
This bug is a mix of #170 and #77. The first one was released in 0.8.5 which makes this issue effectively a duplicate of #77 hence I'm closing this one.

**Closed** 2018-05-18 10:47 UTC
Labels: enhancement
