### ISSUE TITLE
Exception thrown in TestRunnerAgent under Python 3.5.x

### ISSUE THREAD

**Issue by KentDyer-cpi** [nokia/RED#359] opened 2020-01-10 15:14 UTC
After installing the latest update all of my test get the following error

 "[ ERROR ] Calling method 'start_suite' of listener 'C:\Users\kentdyer\AppData\Local\Temp\RobotTempDir5111904004858025428\TestRunnerAgent.py' failed: AttributeError: __exit__"

Is there something i can do to fix this? 
Thanks
Kent

**Comment by michalanglart** [comment] 2020-01-10 15:34
Hi,

what are the versions:
- RED version from which you've updated
- RED version to which you've updated (the newest?)
- Python
- RobotFramework

**Comment by KentDyer-cpi** [comment] 2020-01-10 15:53
updated from not sure, i did not write it down before updating.  should have been the previous build as we try too keep these updated 
updated too   RED - Robot Editor	0.9.2.201912171424	
Robot Framework 3.1.2 (Python 3.5.6 on win32)

**Comment by michalanglart** [comment] 2020-01-10 21:07
This is only reproducible under Python 3.5.x. 

The root cause of the issue is here: https://github.com/nokia/RED/blob/884e7557c3f5a18d3fb4ca6763ddd2ced993a29d/src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/main/python/scripts/TestRunnerAgent.py#L152 for Python 3.5+ we use `os.scandir` (line 160) instead of `os.listdir` (line 178) because the first should be favored over the last one but it was introduced in 3.5. The problem is that we use it inside `with` statment which wouldn't work bacause `os.scandir` supports context manager protocol (https://docs.python.org/3/glossary.html#term-context-manager) since version 3.6.

Overall this results in exceptions being thrown in all 3.5.x versions. We'll fix that by changing the range so that `os.scandir` will be used only in 3.6+.

For the time being consider using newer Python as a workaround for this issue. Unless something is blocking you with the update it would be good idea anyway to have something newer than 3.5.

**Comment by michalanglart** [comment] 2020-02-05 08:10
Fixed in 0.9.3

**Closed by michalanglart** 2020-02-05 08:10 UTC
Labels: bug
