### ISSUE TITLE
Debugging: "RED was unable to find suite where the test could be located" error when debugging project located in IBM Jazz source control

### ISSUE THREAD

**Issue by ahojuk** [nokia/RED#350] opened 2019-11-14 12:55 UTC
System:
Ubuntu 18.04.3 LTS
Eclipse IDE for Enterprise Java Developers. Version: 2018-12 (4.10.0)
Python 3.6.8
robotframework==3.1.2
RED - Robot Editor Version: 0.9.0
PyDev - Python Development environment. Version: 7.2.0

Debugging Robot project  located locally works fine:
![picture2](https://user-images.githubusercontent.com/7523736/70787281-02a73080-1d97-11ea-863d-5a1c1c3bc809.PNG)

Debugging same Test Case but this time  located in IBM Jazz Source Control:
![Jazz_Debugging_Error_1](https://user-images.githubusercontent.com/7523736/68857773-33d70700-06ec-11ea-8920-4c9ddf2679b7.PNG)

![picture22png](https://user-images.githubusercontent.com/7523736/70787954-7dbd1680-1d98-11ea-8899-d5f9037f420b.png)

I think this bug is related to this earlier bug:
Validation not working when project is connected to Jazz source control #201

**Comment by michalanglart** [comment] 2019-11-28 09:20
Hi, can you share the Console ouput from the session with project under Jazz source control?

When resolving #201 we were using a simple feature which was providing a new Eclipse File System similarly to Jazz Source Control and we were able to reproduce and fix those issues. Now I tried to do it again but I'm unable to reproduce - the debugger works as expected on a project similar to yours and stored in our non-file:// file system.

**Comment by ahojuk** [comment] 2019-12-02 13:44
Console Output:
Command: /usr/bin/python3 -m robot.run --listener /tmp/RobotTempDir8386145513041049982/TestRunnerAgent.py:44329 --argumentfile /tmp/RobotTempDir8386145513041049982/args_b591fd03.arg /home/username/eclipse-workspace/RobotTests
Suite Executor: Robot Framework 3.1.2 (Python 3.6.8 on linux)
==============================================================================
RobotTests                                                                    
==============================================================================
RobotTests.RobotTestSuite                                                     
==============================================================================
RobotTests.RobotTestSuite.Tests                                               
==============================================================================
TestCase1      


args_b591fd03.arg -file:
# arguments automatically generated
--suite RobotTests.RobotTestSuite.Tests
--test  RobotTests.RobotTestSuite.Tests.testcase1

**Comment by ahojuk** [comment] 2019-12-02 13:45
Console Output:
Command: /usr/bin/python3 -m robot.run --listener /tmp/RobotTempDir8386145513041049982/TestRunnerAgent.py:44329 --argumentfile /tmp/RobotTempDir8386145513041049982/args_b591fd03.arg /home/username/eclipse-workspace/RobotTests
Suite Executor: Robot Framework 3.1.2 (Python 3.6.8 on linux)
RobotTests
RobotTests.RobotTestSuite
RobotTests.RobotTestSuite.Tests
TestCase1

args_b591fd03.arg -file:

arguments automatically generated
--suite RobotTests.RobotTestSuite.Tests
--test RobotTests.RobotTestSuite.Tests.testcase1

**Comment by michalanglart** [comment] 2019-12-03 11:54
Ok, this does not help much. Can you double-click on the stack elements marked with arrows below and tell us what are the error messages for them?

![1](https://user-images.githubusercontent.com/14932410/70049006-f9b2a400-15cb-11ea-9abd-17a2a1142134.png)

**Comment by ahojuk** [comment] 2019-12-10 13:04
<img width="958" alt="debug_tests" src="https://user-images.githubusercontent.com/7523736/70531740-3b0ffa00-1b5e-11ea-830b-a5bc466c12d3.png">
<img width="958" alt="debug_robottestsuite" src="https://user-images.githubusercontent.com/7523736/70531756-419e7180-1b5e-11ea-887d-5fd9f373e6c5.png">

**Comment by michalanglart** [comment] 2019-12-12 11:42
Can you explain how is it structured? Robot is reporting that it starts a suite under `/home/username/eclipse-workspace/RobotTests/RobotTestSuite` however RED was looking for that in workspace and found that it should be under `/default/RobotTests/RobotTestSuite`, but where is this placed?

**Comment by michalanglart** [comment] 2019-12-12 11:43
It's hard to reproduce it since we do not have possibility to test it against IBM Jazz source control

**Comment by ahojuk** [comment] 2019-12-13 08:26
Correct path is: /home/username/eclipse-workspace/RobotTests/RobotTestSuite
This doesn't exist: /default/RobotTests/RobotTestSuite

<img width="383" alt="folder_structure" src="https://user-images.githubusercontent.com/7523736/70785196-cd98df00-1d92-11ea-904a-d5a747661242.png">

**Comment by michalanglart** [comment] 2019-12-13 08:38
Yes it does not exist in your OS-level file system. However eclipse has a concept of EFS: https://wiki.eclipse.org/EFS and as far as I am aware Jazz is using it by providing own filesystem where URIs has a form of sourcecontrol:// instead of file://. Do you have any paths inside eclipse which looked similaraly to /default/RobotTests/RobotTestSuite ?

**Comment by ahojuk** [comment] 2019-12-13 08:50
Eclipse/Project Explorer/Properties:
![Project_Properties](https://user-images.githubusercontent.com/7523736/70786853-39307b80-1d96-11ea-96b9-0f5cc4323a33.png)

**Comment by michalanglart** [comment] 2019-12-13 12:33
I'm still unable to reproduce the issue however I found suspected place which may be a possible culprit. I've changed the code in this place and build binaries with that. Can you test it in your eclipse? Choose `Help-> Install New Software -> Add... -> Archive...` and then choose downloaded RED feature zip (this almost ready 0.9.2 which we're about to release next week with this small change I've done to check if it would help):

[RED_feature_0.9.2.201912131220.zip](https://github.com/nokia/RED/files/3960751/RED_feature_0.9.2.201912131220.zip)

**Comment by ahojuk** [comment] 2019-12-16 12:54
Tested and now it's working great! Thanks a lot for fixing this!

![working_ok_now](https://user-images.githubusercontent.com/7523736/70908380-bb79a380-2013-11ea-8fb6-8408c89d660e.PNG)

**Comment by michalanglart** [comment] 2019-12-17 08:11
Great to here, I'm pushing the change into master then. It will be available in next version (looks like we'll release it today).

**Comment by michalanglart** [comment] 2019-12-17 15:09
Fixed in 0.9.2

**Closed** 2019-12-17 15:10 UTC
Labels: bug
