### ISSUE TITLE
Autodiscovery function does not work correctly

### ISSUE THREAD

**Issue by AndreasRusjaev** [nokia/RED#81] opened 2017-02-08 09:15 UTC
I have imported in my project  4 Python Libraries
ExtendedSelenium2Library
RequestsLibrary
DatabaseLibrary
base64
Autodiscovery in 0.7.5 founded only DatabaseLibrary. In 0.7.4 all was founded.

**Comment by KrzysztofJozefowicz** [comment] 2017-02-08 10:00
Hi
I looks like you may have and adge case which was not covered with our testes.
We would need as detailed information as possible to reproduce and provide fix:
1. OS type ,python,RF versions
2. how are those libs accessed (by direct path, by relative path with help of python path, by lib name as they were installed by pip)
3. can you provide screenshot/testcase part with settings part ?

**Comment by AndreasRusjaev** [comment] 2017-02-08 10:28
Windows 7 x64
Python 2.7(c:/devtools/Python27 on win32)
Robot Framework 
Libraries was installed with pip into c:/devtools/Python27/lib/site-packages
![red issue](https://cloud.githubusercontent.com/assets/18263592/22733355/b4b6fe0a-edf1-11e6-9bd2-7000b6d8b240.png)

**Comment by KrzysztofJozefowicz** [comment] 2017-02-08 10:31
can you verify our assumption as ExtendedSelenium causes something to Autodiscovery?

Move importing ExtendedSelenium to the bottom of the settings part and check how many libs were discovered?

**Comment by AndreasRusjaev** [comment] 2017-02-08 10:47
If i remove all libraries from red.xml then by discovering.
only DatabaseLibrary was founded.
![before](https://cloud.githubusercontent.com/assets/18263592/22733961/3bd75342-edf4-11e6-9770-0776f728539c.png)
![after](https://cloud.githubusercontent.com/assets/18263592/22733962/3fd66faa-edf4-11e6-9e46-f774b27d80b2.png)

**Comment by AndreasRusjaev** [comment] 2017-02-08 11:07
By my college was the same. 
The libraries was founded if i manual write the libraries into red.xml.
After new start of red i can see all keyword from the libraries.

**Comment by KrzysztofJozefowicz** [comment] 2017-02-08 11:09
Thanks, we are working to provide generic fix.

**Comment by AndreasRusjaev** [comment] 2017-02-08 11:09
Thank You very match.

**Comment by KrzysztofJozefowicz** [comment] 2017-02-22 09:25
@AndreasRusjaev  - we have released a nightly build with fix based on 0.7.5 release. Can you update your RED and check if the fix fixes your issue?
If you use RED in Eclipse as feature, download RED_feature_0.7.5.201702220908.zip, open RED, from help choose "Install New Software", click on Add and with Archive select zip file.
For RED product, just download relevant RED product for your OS. 
Files are only in GitHub, UpdateSite has not been updated with 0.7.5-fix.
https://github.com/nokia/RED/releases/tag/0.7.5-fix

**Comment by AndreasRusjaev** [comment] 2017-02-22 09:45
@KrzysztofJozefowicz - i have bug fix verified. 
The Auto discovery work correctly.
Thank You very match.
![bug-fix-verification](https://cloud.githubusercontent.com/assets/18263592/23205921/fcfc3c52-f8eb-11e6-9216-ab29b64a9198.jpg)

**Comment by KrzysztofJozefowicz** [comment] 2017-02-22 09:47
Thanks,  I will  close this issue than.

**Closed by KrzysztofJozefowicz** 2017-02-22 09:47 UTC
Labels: bug
