### ISSUE TITLE
The default  arguments  of the library's constructor contain Chinese character throw WindowsError: [Error 32]

### ISSUE THREAD

**Issue by kenifanying** [nokia/RED#317] opened 2019-07-18 18:10 UTC
Hi, 

I have a library written in python, and the default  arguments  of the library's constructor contain Chinese character. 

The library can not automatically discovered by Red, it will throw exception if i try to reload the library:

```
Library specification generation problem

Problem occurred during generating libdoc for 'wifi_action' library located at 'C:\Users\tony\robotframework\para-demo\lib\wifi_action.py'.
Following exception has been thrown:
            WindowsError: [Error 32] : 'c:\\users\\tony\\appdata\\local\\temp\\tmplq81ai'
```

I upload the demo project `para-demo.zip`, any assistance would be appreciated.

[para-demo.zip](https://github.com/nokia/RED/files/3407837/para-demo.zip)

Python 2.7.16
Robot Framework 3.1.1 (Python 2.7.16 on win32)
RED - Robot Editor version 0.8.13
System: Windows 7 SP1 X86_64

**Comment by michalanglart** [comment] 2019-07-22 12:36
Hi,

I can confirm that I'm experiencing the same behaviour with your demo project. However the problem is not located in RED. The same problem can be reproduced using only `robot.libdoc` tool from command line - this is pretty much the same what RED does in order to generate library documentation/specification.

Try to generate XML specification file for your `wifi_action` library in command line"

```
python -m robot.libdoc wifi_action.py libdoc.xml
```

in my case it gives:

```
Unexpected error: WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'libdoc.xml'
Traceback (most recent call last):
  File "d:\Programs\python27\lib\site-packages\robot\utils\application.py", line 83, in _execute
    rc = self.main(arguments, **options)
  File "d:\Programs\python27\lib\site-packages\robot\libdoc.py", line 158, in main
    libdoc.save(output, self._get_output_format(format, output))
  File "d:\Programs\python27\lib\site-packages\robot\libdocpkg\model.py", line 53, in save
    LibdocWriter(format).write(self, outfile)
  File "d:\Programs\python27\lib\site-packages\robot\libdocpkg\output.py", line 38, in __exit__
    os.remove(self._output_path)
```

All works under python 3.7 (both from command line and from RED)

**Comment by kenifanying** [comment] 2019-07-22 13:06
So, is this a probem of the robotframework under python 2.7 ?

**Comment by michalanglart** [comment] 2019-07-22 18:12
Yes. It's a RF libdoc bug under 2.7

**Comment by michalanglart** [comment] 2019-07-23 06:39
I'm closing this as there is nothing we can do on RED side. Feel free to open an issue under RF: https://github.com/robotframework/robotframework/ if you are required to stay under python 2.7.

As a side note: both `XML` and `HTML` documentation generation fails with different exceptions. In case of `HTML` the file is not generated at all while under `XML` it is corrupted (missing closing tag for root element). Also it is only files writing affected - `robot.libdoc` is able to read the library properly and this is visible because you may use `python -m robot.libdoc wifi_action.py list` command in order to list available keywords.

**Closed by michalanglart** 2019-07-23 06:39 UTC

**Comment by kenifanying** [comment] 2019-08-08 06:20
> 
> 
> I'm closing this as there is nothing we can do on RED side. Feel free to open an issue under RF: https://github.com/robotframework/robotframework/ if you are required to stay under python 2.7.
> 
Thank you for your reply, I will report a bug to RF.
> As a side note: both `XML` and `HTML` documentation generation fails with different exceptions. In case of `HTML` the file is not generated at all while under `XML` it is corrupted (missing closing tag for root element). Also it is only files writing affected - `robot.libdoc` is able to read the library properly and this is visible because you may use `python -m robot.libdoc wifi_action.py list` command in order to list available keywords.
