### ISSUE TITLE
Dynamic Robot library does not find config file during validation

### ISSUE THREAD

**Issue by chorstmann** [nokia/RED#280] opened 2019-02-26 15:50 UTC
I have a project set up where I generate the Robot keywords dynamically based on a configuration file. This file is located in the project folder. 

During the Library validation in RED I always get a "No such file or directory" error. When I run a test case using the library, the keywords are generated as expected. 

Investigation showed me that the current working directory during validation is the RED installation folder and during test execution it is the project folder. 

I have attached an example project showing the issue I have: [dynamic_example.zip](https://github.com/nokia/RED/files/2906244/dynamic_example.zip)
I have been using RED 0.8.10 installation with PyDev 7.0.3 installed as additional Eclipse plugin. Robot Framework 3.1.1
Edit: Also tested with RED 0.8.11 now. Same issue.

What are my options now?
- Is there a way to configure the working directory for validation in RED?
- I could add some code to prevent the exception. This would have the result that RED does not know any of the libraries keywords. So this is a bad option. I use this approach for Robot libraries with static keywords. 
- Is this a bug in RED? Could you update RED to use the project folder as working directory during validation?

**Comment by michalanglart** [comment] 2019-02-26 22:21
Hi,

in my explanations here whenever I use term `working directory` I mean this: https://en.wikipedia.org/wiki/Working_directory

although your example is quite simple there are lot of things involved in this issue.

1. Validation has no "working directory" it just validates project and files inside it but it's not any kind of external process so there is no "working directory" in this sense

2. When RED is working it starts a simple server in separate process - this server is written in python and it is a kind of a glue between red/eclipse and python/robot worlds. It allows to integrate both tools and provide needed data for RED. For example it is used to generate library specifications files. On server side it uses `robot.libdoc` to generate the file while RED is reading it in order to recognize keywords from that library, provide content assist in editor etc.

3. The server from point above is a separate process so it has its working directory. This directory is inherited from RED - it the same as RED working directory. I cannot tell you what this directory will be since it depends how user starts RED. To see this you can try following in your command line (here in windows):

```
cd path/to/workspace/dynamic_example
path/to/installation/RED.exe
```

when I do it now - your library is properly recognized by RED because is started from project directory (so it is a RED working directory and thus server which generates libdocs have the same ).

4. The working directory of a launched suite is always the project directory in which the suite is contained - that's why everything works in your case when you launch the tests from RED. However there are two flavours how the tests are launched from RED in Robot: 
    - by passing path to directory (this is not a working directory - this is a tests source for Robot) and using `--suite` selectors to choose the suite inside it
    - by passing path to the selected suite inside the project

  the first one is default and it can be changed in preferences.


In my opinion the problem lies in your exemplary library not RED. First of all as I shown you above - RED recognizes this library if it is started from proper directory in command line. But to prove that this problem does not depend on RED let me show you this scenario: we want to use `robot.libdoc` tool (http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#library-documentation-tool-libdoc) to print the list of keywords in exemplary library.

- open command line
- run following:
```
cd dynamic_example
python -m robot.libdoc Libraries/dynamic.py list
```
- the output is:
```
Keyword From Config 1
Keyword From Config 2
```
- now change working directory:
```
cd Libraries
python -m robot.libdoc dynamic.py list
```
- the output is:
```
Getting keyword names from library 'dynamic' failed: Calling dynamic method 'get_keyword_names' failed: FileNotFoundError: [Errno 2] No such file or directory: 'keywords.config'
```

This mean that you cannot reliably use standard `robot.libdoc` tool to get the documentation of this library because whether it will be generated or not depends on the directory from which we run the tool. This is the same for RED.

In general this examplary library consist of a script file and some configuration file and the script opens the file using relative path which is then resolved against working directory (https://docs.python.org/3/library/functions.html#open) so it requires users of this library to start the process from only one working directory (the project path). I think this is wrong - the library script should know where its configuration file is located so that it does not depend on how user started the script.

IMHO the script should do `os.path.realpath(__file__)` and combine it with some relative (to script!) path in order to get absolute path of configuration file and not to depend upon the directory from which user started.

**Comment by michalanglart** [comment] 2019-02-26 22:37
Morever the problem is also visible when running the tests. See screenshot above: the same tests were run from two different locations. First time from `dynamic_example` directory while the second time from its parent directory.

![session](https://user-images.githubusercontent.com/14932410/53451604-79995580-3a1f-11e9-82df-0d6a62646987.png)

**Comment by chorstmann** [comment] 2019-02-27 08:34
Thank you for the detailed explanations. I will use `os.path.realpath(__file__)` to generate a proper path to the config files.

I guess this issue solved now.

**Comment by michalanglart** [comment] 2019-02-27 08:52
Ok, I'm closing it then.

I forgot to write it: thank you for the way you've opened this ticket - there was everything we needed to investigate it further without asking about anything.

**Closed by michalanglart** 2019-02-27 08:52 UTC
