### ISSUE TITLE
Embedded arguments in keywords with Cyrillic

### ISSUE THREAD

**Issue by PavlovNik** [nokia/RED#225] opened 2018-06-14 06:01 UTC
Hi!
I use RED 0.8.5.
I have some problems when I use embedded arguments in keywords with Cyrillic. RED notice "Unknown keyword" when I use it in my test cases. Both files have encoding UTF-8. See screenshot below.
![red](https://user-images.githubusercontent.com/8297700/41393934-384affa6-6fd2-11e8-9ddf-ce135c787daa.png)

How can I сorrect this behavior?

**Comment by michalanglart** [comment] 2018-06-14 06:28
Hi,

let me take a quick look at this issue. If that's something easy to fix we can probably release it with upcoming version today or tomorrow.

**Comment by PavlovNik** [comment] 2018-06-14 06:54
Ok! Thank you.
Looking forward these fix.

**Comment by michalanglart** [comment] 2018-06-14 06:54
Hmm,

Can you share some minimal project? I created something similar to your example both in .robot and .txt files; all encoded with UTF-8 and I can't see this problem - everything is fine, no errors, I'm able to Ctrl+click on keyword and it navigates properly to definition.... 

See project in attachement.
[cyrillic.zip](https://github.com/nokia/RED/files/2101117/cyrillic.zip)

**Comment by PavlovNik** [comment] 2018-06-14 07:30
Change in your 'res.robot' ${arg} to ${argument} and you'll see my problem. For example in Test Case argument can be passed like String.
![red2](https://user-images.githubusercontent.com/8297700/41397784-78e7d3ec-6fdf-11e8-8cee-623dac942278.png)

**Comment by michalanglart** [comment] 2018-06-14 08:35
Ok, thanks for that. I was able to find the cause and it will be fixed in 0.8.6 which we plan to release today or tomorrow.

For future reference - the issue is caused by following line:

https://github.com/nokia/RED/blob/d0f2b115ca165aa0276ba2eb942d8eb62385da2d/src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/main/java/org/rf/ide/core/testdata/model/table/keywords/names/EmbeddedKeywordNamesSupport.java#L74

When we're looking if some name is matching to keyword with embedded arguments we're buildng regular expression out of parameterized name, so that for example `keyword ${var}` becomes regex `(?i)^\Qkeyword \E.+&`. The name which comes to this method is usually lower-cased so because of that the regex have `?i` flag specified in order to make it case-insensitive. This however does not not work for unicode characters and additionally `?u` flag has to be specified as described here: https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#UNICODE_CASE

In this example [Cyrillic Ka](https://en.wikipedia.org/wiki/Ka_(Cyrillic)) is provided in different casing thus causing the method to return false while true is expected.

**Comment by PavlovNik** [comment] 2018-06-14 08:44
Thank you. Waiting for version 0.8.6.

**Comment by michalanglart** [comment] 2018-06-19 09:59
Fixed in 0.8.6

**Closed by michalanglart** 2018-06-19 09:59 UTC
Labels: bug
