### ISSUE TITLE
Unable to find output console when running the test

### ISSUE THREAD

**Issue by ramganesh19** [nokia/RED#369] opened 2020-03-26 23:41 UTC
![image](https://user-images.githubusercontent.com/12521269/77706749-3e09eb80-6f91-11ea-8fb2-43a87ad62f43.png)
An internal error occurred during: "Launching Robot Tests".
Unable to find output console. Trying to look for a console with name:
Login.robot [Robot] C:\Users....\AppData\Local\Programs\Python\Python37\python.exe

C:\Users...>python --version
Python 3.7.7

C:\Users.....>pip --version
pip 20.0.2 from c:\users\saura\appdata\local\programs\python\python37\lib\site-packages\pip (python 3.7)

C:\Users....>pip list
Package Version

pip 20.0.2
robotframework 3.1.2
setuptools 41.2.0

Eclipse IDE for Enterprise Java Developers.

Version: 2020-03 (4.15.0)
Build id: 20200313-1211

Latest RED using Eclipse Marketplace

 I tired resetting the Robot perspective and see both console and message log window open, but i still get error.

**Comment by modrz** [comment] 2020-03-27 05:55
Hi,

This problem is actually a duplicate of #368 

There is a problem with RED on newest Eclipse platform which we already fixed.
You can try attached development version of RED from #368

**Comment by michalanglart** [comment] 2020-04-28 11:40
Fixed in 0.9.4

**Closed by michalanglart** 2020-04-28 11:40 UTC
Labels: duplicate
