### ISSUE TITLE
FATAL: Missing suite file for execution, current suite name: 'Test_Designs', current keyword: '${i} IN RANGE [ ${timeout} ]' typ='For' args=[]

### ISSUE THREAD

**Issue by k0enf0rNL** [nokia/RED#29] opened 2016-07-05 09:50 UTC
![red error](https://cloud.githubusercontent.com/assets/11920266/16580864/d60f1642-42a6-11e6-9ed9-94fb9b1dadfd.PNG)
This keywords does work in RIDE. I can't tell if i'm missing an import or I found a bug.

**Comment by adam-wypych** [comment] 2016-07-05 09:56
Hi,

Can You put an example test suite content, which fails? It is during debug or You just simple try to run it?

BR,
-Adam.

**Comment by k0enf0rNL** [comment] 2016-07-05 10:37
${timeout}    Timestr To Secs    ${timeout}
    Set timeout    ${timeout}
    : FOR    ${i}    IN RANGE    ${timeout}
    \    ${pass1}    ${msg1}=    Run Keyword And Ignore Error    Wait Until Element Is Visible    ${locator}    1
    \    ${pass2}    ${msg2}=    Run Keyword And Ignore Error    Is Element Clickable    ${locator}
    \    ${clickable}=    Set Variable If    '${pass1}' == 'PASS' and '${pass2}' == 'PASS'    ${True}    ${False}
    \    Run Keyword If    ${clickable}    Exit For Loop
    \    Sleep    1s
    \    Exit for loop if timeout
    #    Take screenshot to show why failed to click element.
    Run Keyword Unless    ${clickable}    Fail    msg=Element '${locator}' is not clickable

this is the keyword where it fails in. It only happens when running in debug mode.
I'm using version 0.6.5 Robot Framework verison 3.0.

**Comment by adam-wypych** [comment] 2016-07-05 11:40
Hi,

Thanks for update, this is bug for ensure. 
We found the problem is connected to `__init__.*` file located inside Your Test_Designs directory with `:FOR` loop. We will try to fix it ASAP.

Best Regards,
-Adam.

**Comment by adam-wypych** [comment] 2016-07-08 04:05
@k0enf0rNL: Can You check if it works with new release 0.6.5?

**Comment by adam-wypych** [comment] 2016-07-13 07:01
@k0enf0rNL: Any progress so far?

**Comment by k0enf0rNL** [comment] 2016-07-26 11:00
@adam-wypych Seems to be working with the new release 0.6.5. How can I use the debug mode to run the test step by step like the normal eclipse debugger?

**Comment by adam-wypych** [comment] 2016-07-26 11:09
@k0enf0rNL Yes you should be able to see, which keyword is executed and in case keyword is not any source code, You will be even able to perform `step in`. For further information please see: https://github.com/nokia/RED/blob/master/red_help/user_guide/debug.html.md . If something is unclear please inform us. Thanks in advance.

**Comment by KrzysztofJozefowicz** [comment] 2016-07-28 13:12
@k0enf0rNL - I will close the issue as you stated that it is working in 0.6.5

**Closed by KrzysztofJozefowicz** 2016-07-28 13:12 UTC
Labels: bug
