### ISSUE TITLE
When editting off screen, focus flips back to the left

### ISSUE THREAD

**Issue by pbbos** [nokia/RED#38] opened 2016-09-06 19:09 UTC
When editting a value that is off my screen (so i have use the scrollbar to move the focus to the right), the scrollbar automaticly flips back to the left.
That way i have to scroll to the right again, for every value i want to edit or add that's off screen.

Eclipse Java EE IDE for Web Developers.
Version: Luna Service Release 2 (4.4.2)
Build id: 20150219-0600

Java 1.7.0_80-b15
Python 2.7.11
RED - Robot Editor version 0.6.5 
Win 7 pro 64 bit

**Comment by adam-wypych** [comment] 2016-09-07 04:01
During which table editing You've been discovered this problem?

**Comment by pbbos** [comment] 2016-09-07 04:33
In source view.

**Comment by KrzysztofJozefowicz** [comment] 2016-09-07 09:05
Hi
I could not reproduce your issue. Can you provide steps to reproduce it?
What I have tried in Source tab:
 - create empty robot file, create TC input long lines with spaces, double spaces and tabs,the same with Documentation and KW
 - create empty tsv file, the same as above.


I used Eclipse Java EE Luna Version: Luna Service Release 2 (4.4.2) Build id: 20150219-0600 and also Eclipse Java EE Neon (latest) with RED 0.6.5 release from GitHub.

**Comment by pbbos** [comment] 2016-09-10 06:36
Hi

It took me some time to find out why you cannot reproduce the issue, but i made an example.
Looks you're only able to reproduce it, when you are editting a file of a certain length.

With the script below, i'm able to reproduce it also on a windows10 machine with Eclipse Neon and red 0.6.5.

Copy the script below to a robot file and try to add something on the last line I called 'A LONG LINE THAT IS AN EXAMPLE TO SHOW THE BUG'.

I haven't found out what is the real cause, but I hope you can at least reproduce it now:

*** Settings ***
Library							DatabaseLibrary
Library							Selenium2Library
Library							DateTime
Library							OperatingSystem
Documentation					Grabber
Resource						${CURDIR}${/}..${/}..${/}resources${/}keywords.robot
Resource						${CURDIR}${/}tera_user.robot
Suite Setup						Run Keywords	Connect to DB TeraDataVM780	
Test Template					Copy Table

*** Variables ***
${DESTINATION}					STR13_ONT
${SOURCE}						STR11_ONT
${MAXIMUM}						100000000

#************************ DATABASE (Teradata VM 780)*********************
${TERADATA_CLASS}				com.teradata.jdbc.TeraDriver
@{VM-TD_DB_CONNECT_STRING}		jdbc:teradata://o123.ont.dev.nl/CHARSET=UTF8          ${VM-TD_USER}    ${VM-TD_PASSWORD}
@{DB-DRIVERS}					${CURDIR}${/}..${/}teradata${/}terajdbc4.jar                  ${CURDIR}${/}..${/}teradata${/}tdgssconfig.jar

*** Keywords ***
Connect To DB TeraDataVM780
	Connect To Database Using Custom Params		jaydebeapi  '${TERADATA_CLASS}', @{VM-TD_DB_CONNECT_STRING}, @{DB-DRIVERS}
	Execute Sql String							DATABASE ${DESTINATION}
	
Copy Table
	[Arguments]		${table}	${source}	${target}		${where}
	Execute Sql String 	DELETE FROM ${target}.${table} ${where}
	Execute Sql String 	INSERT INTO ${target}.${table} SELECT * FROM ${source}.${tabelnaam} ${where}

*** Test Cases ***
XXXXX_1        XXXXX_1        ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_2        XXXXX_2        ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_3        XXXXX_3        ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_4        XXXXX_4        ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_5        XXXXX_5        ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_6        XXXXX_6        ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_7        XXXXX_7        ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_8        XXXXX_8        ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_9        XXXXX_9        ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_10       XXXXX_10       ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_11       XXXXX_11       ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_12       XXXXX_12       ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_13       XXXXX_13       ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_14       XXXXX_14       ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_15       XXXXX_15       ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_16       XXXXX_16       ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_17       XXXXX_17       ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_18       XXXXX_18       ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_18_01    XXXXX_18_01    ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_18_02    XXXXX_18_02    ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_19       XXXXX_19       ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_20       XXXXX_20       ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_21       XXXXX_21       ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_21_01    XXXXX_21_01    ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_22       XXXXX_22       ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM}
XXXXX_23       XXXXX_23       ${SOURCE}    ${DESTINATION}    WHERE IDNR < ${MAXIMUM} A LONG LINE THAT IS AN EXAMPLE TO SHOW THE BUG

**Comment by pbbos** [comment] 2016-09-12 05:55
@KrzysztofJozefowicz are you able to reproduce it now?

**Comment by adam-wypych** [comment] 2016-09-12 05:57
@pbbos Krzysztof is not currently in the office, but I've been checked it with `.robot` format and yes I see what happen that horizontal slider dance :)

**Comment by KrzysztofJozefowicz** [comment] 2016-09-12 07:40
Thanks. it is reproducible although we did not see that behavior previously as our screen are wide enough.
We will investigate it and decide if we are able to provide fix for upcoming 0.7.0 release or postpone it to later release.

**Comment by KrzysztofJozefowicz** [comment] 2016-09-14 11:39
released in 0.7.0

**Closed by KrzysztofJozefowicz** 2016-09-14 11:39 UTC
Labels: bug
