### ISSUE TITLE
Where are sources?

### ISSUE THREAD

**Issue by paulvi** [nokia/RED#11] opened 2016-03-25 15:09 UTC
Where are sources?

**Comment by adam-wypych** [comment] 2016-03-29 05:52
Hello,

currently we decided to postpone publishing RED sources until table and source editor will be in place. 

Anyway, can you described why do you need RED sources?

**Comment by paulvi** [comment] 2016-03-30 01:24
If you point users to GitHub link, general expectation is that sources are there, and user may rest assured that this project will not disappear one day because of some business reasons and no sources are left to continue.

I don't need sources. Especially when they are not open-sourced.

Just came here to learn about knew project and found strange thing.

**Comment by adam-wypych** [comment] 2016-03-30 04:58
I didn't say that source code is in the place, but I think you miss the point here. 

As I said source code will be published after table editor will be in place, from my experience we do not want to create next Python2 to Python3 migration problem. Next think is that you did not completly described for me why you need sources. As you can read RED is IDE to work with Robot Framework, so for me strange was here that source code is, so required for somebody - I see only two valid options fix the bug or extend functionality. For any of them please create GitHub issue ticket.

For most of the community Open Source is not only source code published some where with a lot of legal issues and copyright in place, but also free to use binary (if somebody required mainly from testers to setup build system environment and create executable files - it hit own foot with own gun), or in GitHub you can't publish the first binaries and after source?

**Comment by pekkaklarck** [comment] 2016-06-01 11:21
I don't know what is GitHub's stance about having source code available, but it is definitely true that a project is not open source if you cannot access its source code. For more information see the [Open Source Definition](https://opensource.org/osd-annotated).

**Comment by adam-wypych** [comment] 2016-06-02 07:43
@pekkaklarck We didn't say that source code is currently available, **but our intention is to publish it** after table editor will be in place. From description of Open Source you can read that _**Where some form of a product is not distributed with source code, there must be a well-publicized means of obtaining the source code** for no more than a reasonable reproduction cost preferably, downloading via the Internet without charge. (...) Deliberately obfuscated source code is not allowed. Intermediate forms such as the output of a preprocessor or translator are not allowed_. I gave short example that in community life better than be, so strict is to keep in mind that is easy is to publish prototype, but withdraw what is in use is not so easy - this is what even Joshua Bloch propose in they lecture about being API designer.

Anyway sorry that You can access currently source code, hope soon we will be able to show world how RED works.

**Comment by pekkaklarck** [comment] 2016-06-02 08:21
Do you have "well-publicized means of obtaining the source code"? If yes, I would think just having the source code available here would be easier. If not, you don't comply with the Apache 2 license.

Notice that I'm personally not interested about the source code and wouldn't mind if RED or any other tool in the Robot Framework ecosystem wouldn't be open source in the first place. I just want to underline that it is confusing to claim that something is open source if the source code isn't available.

Finally, I don't understand the problem with non-stable APIs in this regard. You could simply state that all APIs are currently non-stable and can be modified or even removed totally in future versions. You can then later start labeling APIs stable and public if you want.

**Comment by adam-wypych** [comment] 2016-06-02 08:39
@pekkaklarck 
About your first point as I understand Apache 2 license means also free to use software, so I do not understand why we still talk about being or not comply if source is not available. If our intention is that it will be published anybody can modify it and use as Apache 2 license state, I will not to be so pedantic if even You stays _You can then later start labeling APIs stable and **public if you want**._, the answer is we want to do this as more stable as it will be currently.

Next if you agree that open source statement that publisher can from some reason do not publish code from well describe reason for me confuse is that even is defined we need to say it again, or I miss sth?

About non-stable API is that people do not read what authors of software say, they just use and this is how it works. For more information please watch: https://www.youtube.com/watch?v=heh4OeB9A-c .

**Comment by pekkaklarck** [comment] 2016-06-02 09:03
Do you have "well-publicized means of obtaining the source code"?

**Comment by adam-wypych** [comment] 2016-06-02 11:40
Yes, and it was described few times - current core part of RED is changing, so much that publish it now will made a lot of more confusion than about lack of source code. If You want to contribution from anybody You can't simple do not care what You plan to do and how it will be affect others. I agree that source code shouldn't be dead and changing is normal software project life, but in case You have on table decission to postpone a little bit and release stable or release just to fill some guidelines, I think better is to wait a little bit. As You said You are not personal interested in source code of RED and most of users also, this is tool for RF test case development.

Anyway I think better is to focus for now on 99% of users using RED as editor than give a lot of bigger prority to keep promise that source code released must not create impact on followers.

From few weeks we are focused on table editor and to keep also Your guideline about update only change area and leave as it was the part, which user didn't modify. Therefore we are changing not only plugins to table view, but also parse/dump part of RED is modified. 

Why are do our best to finish it as soon as possible. Thanks for understanding and sorry that You are feel confused. Publish source code is our goal, which we will soon achieve.

**Comment by adam-wypych** [comment] 2016-07-08 04:11
Hi,

I happy to say that now source code is available since the first 2 grid tables was introduce.

@pekkaklarck , @paulvi thanks for Your patient.

-Adam.

**Closed by adam-wypych** 2016-07-08 04:11 UTC
Labels: question

**Comment by pekkaklarck** [comment] 2016-07-26 22:05
:fireworks:
