### ISSUE TITLE
issue with eclipse update

### ISSUE THREAD

**Issue by ddelpha** [nokia/RED#368] opened 2020-03-26 22:10 UTC
Hello, 
Yesterday eclipse updated to 202003 and it is now causing issues with RED for me. I didn't have any issues before today and even unistalled/reinstalled eclipse 2 times to be sure. 

The following occurs when i try to run a .robot file in Eclipse that worked yesterday.

An internal error occurred during: "Launching Robot Tests".
Unable to find output console. Trying to look for a console with name:
ContactForm.robot (Selected Test Cases) [Robot] /usr/bin/python3

For extra clarification my console 'name' for this test is ContactForm.robot (Selected Test Cases) [Robot] 
Is this a case of Red not being configured for the update?

Thank you

**Comment by modrz** [comment] 2020-03-27 05:52
Hi,

We know about this problem with RED on Eclipse platform 2020-03.
It has bean already fixed, you can wait for official release or try following development version:

[RED_feature_0.9.4.202003261232.zip](https://github.com/nokia/RED/files/4391745/RED_feature_0.9.4.202003261232.zip)

**Comment by michalanglart** [comment] 2020-03-27 06:27
As a side note: we're actually ready to release next version which would fix it, but we're waiting for Robot Framework release 3.2. Newest date for that release we've seen is in 2 weeks - around 6th April

**Comment by ddelpha** [comment] 2020-03-27 06:31
Thank you @modrz and @michalanglart for your response. I will standby until after the 6th, keep up the good work!

**Comment by SwanandP-code** [comment] 2020-04-08 06:02
i am facing same issue is there any updates on this issue
when it will be fixed

**Comment by michalanglart** [comment] 2020-04-08 06:06
Hi, I stated that before:
> we're waiting for Robot Framework release 3.2

They still haven't released final version, seems that it's going to happen next week

**Comment by SwanandP-code** [comment] 2020-04-08 06:07
so is there alternative way or solution to resolve this issue

**Comment by ddelpha** [comment] 2020-04-08 06:07
@SwanandP-code  in the meantime you can run those files through vscode. I write them in eclipse/red which still works then run the scripts in vscode to test.

**Comment by michalanglart** [comment] 2020-04-08 06:15
> so is there alternative way or solution to resolve this issue

Of course there is: simply use eclipse 2019-12 instead of 2020-03, or RED product (one of RED_0.9.3.xxxxxxxxxxxx.zip zips depending on your OS from https://github.com/nokia/RED/releases/tag/0.9.3)

**Comment by SwanandP-code** [comment] 2020-04-08 06:16
will it work with older version of eclipse??

**Comment by michalanglart** [comment] 2020-04-08 06:19
Sure, of course: RED is working with following versions (chronological order): Oxygen (4.7), Photon (4.8), 2018-09 (4.9), 2018-12 (4.10), 2019-03 (4.11), 2019-06 (4.12), 2019-09 (4.13), 2019-12 (4.14).

This issue will occur when using 2020-03 (4.15)

**Comment by michalanglart** [comment] 2020-04-08 06:20
You can use 2019-12 with RED and once we release next version you can also update eclipse to 2020-03.

**Comment by chitsit** [comment] 2020-04-13 08:07
Please update if the issue has got resolved for Eclipse 2020-03.

**Comment by MishSwati** [comment] 2020-04-14 08:31
Issue is not resolved yet. I check just now , I am still getting the same error

**Comment by filipefialhosilva** [comment] 2020-04-21 10:29
Still not resolved. 
An internal error occurred during: "Launching Robot Tests".
Unable to find output console. Trying to look for a console with name:

**Comment by michalanglart** [comment] 2020-04-21 10:43
Hi, yes this issue is precisely about the error you've experienced.

As already stated in the discussion:

1) this error occurs once Eclipse 2020-03 is used, so older e.g. 2019-12 can be used to avoid it
2) one can install RED unofficial build attached in this comment: https://github.com/nokia/RED/issues/368#issuecomment-604828040
3) the issue is fixed and waiting for the release; but we're waiting for Robot too because we wanted this release to fully support RF 3.2. Unfortunately the release date of Robot 3.2 was rescheduled couple of times, but we hope it will be finally released within a week.

**Comment by anafaguaga** [comment] 2020-04-24 18:29
Hello, I have installe de all the package for Eclipse, robot framework et RED this week and the problem of unable to find output console .. is still there. 
Do some ones know when new version of Robot framwork will be released and the patch for Eclipse ?
I need to start some automation for the company I work with a POC with Robot Framwork but I can't work.
Should I download an old version of Eclipse ?  or I just have to take an older version of RED with Eclipse 2020-03 ? I am pretty new in this things.
Thank you ! 
Ana

**Comment by michalanglart** [comment] 2020-04-24 18:40
Hi,

1. older version of RED on 2020-03 will not help
2. older version of Eclipse will help (2019-12)
3. you can install have 2020-03 and install not-released under development version of RED attached in this comment: https://github.com/nokia/RED/issues/368#issuecomment-604828040; install it using instructions in paragraph **Install from zip file** at: http://nokia.github.io/RED/help/first_steps/download_install.html 
4. as stated here: https://groups.google.com/forum/#!topic/robotframework-users/ANBvH6LaX24 Robot release is expected to happen on monday

**Comment by anafaguaga** [comment] 2020-04-24 18:43
Thank you very much!! you are great !! 
I could wait anyways some days but not for two week. I will keep your instructions in case the now version will not be released as soon as expected ..
thank you again !! :) Happy to see as very good professinals in the area.. congrats for your job !!

**Comment by xWilliamsx** [comment] 2020-04-27 13:39
Is there a planned time for today's release?

**Comment by michalanglart** [comment] 2020-04-27 13:44
RF 3.2 was released minutes ago. We'll need to install it and run our tests with it first. If everything would run smoothly, we'll make a release tommorow

**Comment by HackYe** [comment] 2020-04-27 17:12
I am looking forward to the release of a new version, I hope to soon!

**Comment by Anum-Zargar** [comment] 2020-04-28 05:40
Hi,

I am facing the similar issue An internal error occurred during: "Launching Robot Tests".
Unable to find output console. Trying to look for a console with name:
TestSuite1.robot (Selected Test Cases) [Robot] C:\Users\Anum Zargar\AppData\Local\Programs\Python\Python38-32\python.exe

Any idea what should i do.I should use the lower version of eclipse or what

**Comment by michalanglart** [comment] 2020-04-28 07:19
Hi,

> Any idea what should i do. I should use the lower version of eclipse or RED framework

I've already answered this question at least 5 times in this thread. Here are the links which may help to navigate this page:

1. here: https://github.com/nokia/RED/issues/368#issuecomment-619180438
2. https://github.com/nokia/RED/issues/368#issuecomment-617101012
3. https://github.com/nokia/RED/issues/368#issuecomment-610773493
4. https://github.com/nokia/RED/issues/368#issuecomment-610773174
5. https://github.com/nokia/RED/issues/368#issuecomment-610771981

Also as stated here https://github.com/nokia/RED/issues/368#issuecomment-619995600 yesterday we're planning to release new RED today so this issue will be fixed

**Comment by michalanglart** [comment] 2020-04-28 11:40
This is now fixed. Please update RED to 0.9.4

**Closed by michalanglart** 2020-04-28 11:40 UTC
Labels: bug

**Comment by Anum-Zargar** [comment] 2020-04-28 17:28
Hi Michalangart,

Can you please tell me .what i need to do.

How will i add 0.92 version here.

[image: image.png]

**Comment by anafaguaga** [comment] 2020-04-28 18:41
We should install new version of Robot Framework too ? or not necessary ?
It is necessary to uninstall eclipse and install again or I just need to unistall red and reintall it ? ( I have installed RED from Eclipse makretplace )
I am new in all that.. so I am a little lost.

**Comment by michalanglart** [comment] 2020-04-28 19:39
If there is nothing specific in your environment (e.g. proxies) simply click Help -> Check For Updates. This should find that there is newer RED available and simply proceed with next buttons. There is no need to uninstall anything. 

There is also no need to udate Robot to version 3.2 - this is not related at all. The only thing newer Robot was mentioned in this thread was because we were waiting for it be released because we wanted to make sure RED is supporting new version of Robot, but again - it is not related to this issue.

**Comment by anafaguaga** [comment] 2020-04-28 20:09
good, thank you for you help !! I will try that :)

**Comment by Anum-Zargar** [comment] 2020-04-28 20:10
Thanks michanlanglart.
My console problem is solved.

FirstSeleniumTest                                                     |
FAIL |
SessionNotCreatedException: Message: session not created: This version of
Chrome Driver only supports Chrome version 76.But i usually get this
error.what can i do

**Comment by michalanglart** [comment] 2020-04-28 20:14
I'm not an export on Selenium but from message it seems that there is some mismatch between your chrome version and chromedriver version. Check version of your chrome and download chromedriver which would support it.

**Comment by Anum-Zargar** [comment] 2020-04-28 20:20
Sure thanks it solved my problem.I downgrade the version.

**Comment by anafaguaga** [comment] 2020-04-30 13:52
Hello, I have had this message Could not create the view: org.robotframework.ide.MessageLogView.
is it for the proxy, I have a proxy but when I have intalled eclipse, I have put the references needed.
Now I got that after update RED for new version.
I will close and open again to see if it will work . but if you have an idea. would be welcome. :)

**Comment by anafaguaga** [comment] 2020-04-30 13:52
java.lang.Exception
	at org.eclipse.ui.internal.ViewReference.createErrorPart(ViewReference.java:114)
	at org.eclipse.ui.internal.ViewReference.createPart(ViewReference.java:100)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPart(CompatibilityPart.java:300)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:338)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:1002)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:967)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:139)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:408)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:331)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:1002)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:662)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$1.run(PartRenderingEngine.java:547)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:531)
	at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.createWidget(ElementReferenceRenderer.java:73)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:1002)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:662)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:768)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:739)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:733)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showTab(StackRenderer.java:1297)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.postProcess(LazyStackRenderer.java:105)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:680)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:768)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:739)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:733)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:71)
	at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:148)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:676)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:768)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:739)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:733)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:71)
	at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:148)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:676)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:768)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:739)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:733)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:71)
	at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:148)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:676)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:768)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:739)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:733)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:71)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveRenderer.processContents(PerspectiveRenderer.java:51)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:676)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:768)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:739)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:733)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveStackRenderer.showTab(PerspectiveStackRenderer.java:82)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.postProcess(LazyStackRenderer.java:105)
	at org.eclipse.e4.ui.workbench.renderers.swt.PerspectiveStackRenderer.postProcess(PerspectiveStackRenderer.java:64)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:680)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:768)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:739)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:733)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:71)
	at org.eclipse.e4.ui.workbench.renderers.swt.SashRenderer.processContents(SashRenderer.java:148)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:676)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:768)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:739)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:733)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.workbench.renderers.swt.SWTPartRenderer.processContents(SWTPartRenderer.java:71)

**Comment by anafaguaga** [comment] 2020-04-30 14:01
java.lang.Exception
at org.eclipse.ui.internal.ViewReference.createErrorPart(ViewReference.java:114)
at org.eclipse.ui.internal.ViewReference.createPart(ViewReference.java:100)
at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPart(CompatibilityPart.java:300)
at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:338)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:1002)
at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:967)

**Comment by anafaguaga** [comment] 2020-04-30 18:47
look like it is working for me, I had to re intall Eclipse to fix some problems I had.

thanks !
