### ISSUE TITLE
Can't delete a referenced library after moving a Robot project

### ISSUE THREAD

**Issue by Biiosense** [nokia/RED#272] opened 2019-02-06 09:21 UTC
I had a Robot project, working well. 

I moved by hand my project to another location and tried to opened it again. Obviously, my referenced libraries paths were broken (because I've never understood how to make them project-based) 
I want to Delete them properly to add them again, but the interface doesn't allow me to do so ! 
When I click any Delete button, nothing is happening. 
Same for Paths based on Project ! 

The variables files worked.

**Comment by Biiosense** [comment] 2019-02-06 09:23
Python : 2.7
Eclipse : 4.7.3a
RED : 0.8.7.20180807006

**Comment by michalanglart** [comment] 2019-02-07 07:15
Hi,

as of now the project-relative paths to referenced libraries are only used when the library is inside the project.

We need to reproduce that issue on our side. As a workaround you may delete those paths manually by the source of red.xml file.

**Comment by michalanglart** [comment] 2019-02-07 07:22
If I understand correctly: you moved your project to different location? How exactly? By moving it on operating system level? Was eclipse running when you did it? Have you restarted it?

**Comment by Biiosense** [comment] 2019-02-07 10:11
My libraries are inside the project, but when I add them in red.xml, they are registered as absolute and I got an error message saying that paths are absolute and should be relatives. How to m ake them project-relatives ? 
I tried to delete them in red.xml file. 

What I did.
1) I moved my workspace AND my project. 
I deleted projects in my previous Eclipse workspace. I exited Eclipse. I moved my project to new location. I moved my workspace to new location. I opened Eclipse with the new workspace. I added my project from new location. 
Here my referenced libraries were pointing to the old location of my project. 

2) Tried to workaround
I closed Eclipse. I deleted the referenced libraries in red.xml. Start Eclipse. Open red.xml in Eclipse: they are gone. I added them with new path. Here, the libraries are added but they are pointing to the old location, so same error is occurring ! 
I think it is because they have the same name and somewhere those library names are associated to the old locations.

**Comment by michalanglart** [comment] 2019-02-07 10:26
I was imprecise: the referenced libraries are stored with relative path to workspace if those libraries are contained in this workspace. If you for example happen to store libraries inside the project but the project directory outside of workspace directory then the paths will be written in absolute form (since the libraries are not contained in workspace directory in this case).

**Comment by Biiosense** [comment] 2019-02-08 15:46
I still can't delete my references libraries. 
The Delete action doesn't do anything in red.xml.

**Comment by michalanglart** [comment] 2019-02-08 16:13
I was trying to reproduce your issue today but without much luck. Are you able to reproduce it using fresh workspace and some simple project? If so - could you describe the scenario in details?

**Comment by Biiosense** [comment] 2019-02-12 08:30
I was able to reproduce this situation easily just by creating a new project, inside a new workspace. There I add a library located inside the project, and try to remove it. The Delete button doesn't work so the problem might comes from my installation. 
Actually all right-click actions don't work in red.xml. In Validation window, I can't Inlude or Exclude. I need to do it in the Project Explorer window. 

I was able to deal with my problem, by restoring my initial project (in the old workspace), delete the libraries and paths with key SUPPR (Delete button still doesn't work), move the project again, and open the project from the new location with the new workspace. There, I could add libraries from the new location without any problems and now it is working

**Comment by michalanglart** [comment] 2019-02-12 12:36
I'm still unable to reproduce it. The actions in context menu are enabled but clicking on them does nothing? Do you have any errors logged in your `workspace\metadata\.log` file?

**Comment by Biiosense** [comment] 2019-02-12 15:43
When I right-click on a referenced library, the buttons appear. If I click on the Delete Button, the menu disappear and nothing happen. There is no error logged in .log file.

**Comment by michalanglart** [comment] 2019-02-18 10:59
What's your underlying operating system?

**Comment by Biiosense** [comment] 2019-02-19 10:01
Linux Redhat 12

**Comment by michalanglart** [comment] 2019-02-19 10:13
And does your RED/eclispe use GTK3? Please have a look here: http://nokia.github.io/RED/help/user_guide/known_issues.html#gtk3-issues-under-linux

**Comment by Biiosense** [comment] 2019-02-19 11:15
Yes this was the problem. Now the buttons are working and actions are smoother. The interface is different but it's fine. 
Thank you for helping !

**Closed** 2019-02-19 13:32 UTC
Labels: help wanted
