### ISSUE TITLE
RED.xml - Library specification file was not generated for 'Library.class.name' library

### ISSUE THREAD

**Issue by thangaroja** [nokia/RED#265] opened 2018-12-18 08:44 UTC
Hi
    
    Red.xml - I get this error when uploading the java jar files using the button Add Java Library. 

    "Library specification file was not generated for 'Library.class.name' library"

    Tried the below steps,
    1) Removed Build Automatically from Eclipse and did Project - > Clean
    2) Re-Exported the jar file of java class files.

    Note: When built from Shell script, i was able to build and execute the same code successfully. 
    Somewhere when building the class files this issue occurs. But unsure how to rectify it.

**Comment by michalanglart** [comment] 2018-12-18 15:35
Try to find this library in Project Explorer under `Robot Referenced libraries` entry (it should be red). Try clicking `Reload` from context menu of this library. Does this help? If not then what is the error?

Is it possible for you to share this library jar or its crippled version with us??

**Comment by thangaroja** [comment] 2018-12-19 03:41
Thanks @michalanglart  for your response. I followed to Reload the library. But failed. Below is the error detail i received. 

Library specification generation problem

Problem occurred during generating libdoc for 'com.KTOC.TRB.testautomation.Keywords.Keywords' library located at '/Users/roja/Automation/Jars-For-KTOC/TRBJars1.jar'.
RED python session problem. Following exception has been thrown by python service:
            Traceback (most recent call last):
              File "/var/folders/dv/nnfc_k29377bv7s34kng7qgh0000gn/T/RobotTempDir8808901746972554502/robot_session_server.py", line 38, in inner
                result['result'] = func(*args, **kwargs)
              File "/var/folders/dv/nnfc_k29377bv7s34kng7qgh0000gn/T/RobotTempDir8808901746972554502/robot_session_server.py", line 84, in inner
                return to_call(*args, **kwargs)
              File "/var/folders/dv/nnfc_k29377bv7s34kng7qgh0000gn/T/RobotTempDir8808901746972554502/robot_session_server.py", line 116, in inner
                return to_call(*args, **kwargs)
              File "/var/folders/dv/nnfc_k29377bv7s34kng7qgh0000gn/T/RobotTempDir8808901746972554502/robot_session_server.py", line 59, in inner
                return func(*args, **kwargs)
              File "/var/folders/dv/nnfc_k29377bv7s34kng7qgh0000gn/T/RobotTempDir8808901746972554502/robot_session_server.py", line 305, in create_libdoc
                return red_libraries.create_libdoc(libname, format)
              File "/private/var/folders/dv/nnfc_k29377bv7s34kng7qgh0000gn/T/RobotTempDir8808901746972554502/red_libraries.py", line 64, in create_libdoc
                raise Exception(result)
            Exception: Importing test library 'com.KTOC.TRB.testautomation.Keywords.Keywords' failed: NoClassDefFoundError: org/openqa/selenium/WebDriverException
            java.lang.NoClassDefFoundError: 
            	at java.lang.Class.forName0(Native Method)
            	at java.lang.Class.forName(Class.java:348)
            	at robot.utils.importer$py._import$14(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/utils/importer.py:167)
            	at robot.utils.importer$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/utils/importer.py)
            	at robot.utils.importer$py.import_$32(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/utils/importer.py:274)
            	at robot.utils.importer$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/utils/importer.py)
            	at robot.utils.importer$py._import_class_or_module$5(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/utils/importer.py:77)
            	at robot.utils.importer$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/utils/importer.py)
            	at robot.utils.importer$py.import_class_or_module$4(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/utils/importer.py:74)
            	at robot.utils.importer$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/utils/importer.py)
            	at robot.libdocpkg.robotbuilder$py.build$2(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/libdocpkg/robotbuilder.py:40)
            	at robot.libdocpkg.robotbuilder$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/libdocpkg/robotbuilder.py)
            	at robot.libdocpkg$py.LibraryDocumentation$1(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/libdocpkg/__init__.py:47)
            	at robot.libdocpkg$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/libdocpkg/__init__.py)
            	at robot.libdoc$py.main$4(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/libdoc.py:163)
            	at robot.libdoc$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/libdoc.py)
            	at robot.utils.application$py._execute$10(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/utils/application.py:94)
            	at robot.utils.application$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/utils/application.py)
            	at robot.utils.application$py.execute$9(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/utils/application.py:79)
            	at robot.utils.application$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/utils/application.py)
            	at robot.libdoc$py.libdoc$9(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/libdoc.py:223)
            	at robot.libdoc$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages/robot/libdoc.py)
            	at red_libraries$py._create_libdoc_with_stdout_redirect$5(/private/var/folders/dv/nnfc_k29377bv7s34kng7qgh0000gn/T/RobotTempDir8808901746972554502/red_libraries.py:83)
            	at red_libraries$py.call_function(/private/var/folders/dv/nnfc_k29377bv7s34kng7qgh0000gn/T/RobotTempDir8808901746972554502/red_libraries.py)
            	at red_libraries$py.create_libdoc$4(/private/var/folders/dv/nnfc_k29377bv7s34kng7qgh0000gn/T/RobotTempDir8808901746972554502/red_libraries.py:66)
            	at red_libraries$py.call_function(/private/var/folders/dv/nnfc_k29377bv7s34kng7qgh0000gn/T/RobotTempDir8808901746972554502/red_libraries.py)
            	at SimpleXMLRPCServer$py._dispatch$15(/usr/local/Cellar/jython/2.7.1/libexec/Lib/SimpleXMLRPCServer.py:422)
            	at SimpleXMLRPCServer$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/SimpleXMLRPCServer.py)
            	at SimpleXMLRPCServer$py._marshaled_dispatch$10(/usr/local/Cellar/jython/2.7.1/libexec/Lib/SimpleXMLRPCServer.py:276)
            	at SimpleXMLRPCServer$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/SimpleXMLRPCServer.py)
            	at SimpleXMLRPCServer$py.do_POST$19(/usr/local/Cellar/jython/2.7.1/libexec/Lib/SimpleXMLRPCServer.py:535)
            	at SimpleXMLRPCServer$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/SimpleXMLRPCServer.py)
            	at BaseHTTPServer$py.handle_one_request$7(/usr/local/Cellar/jython/2.7.1/libexec/Lib/BaseHTTPServer.py:345)
            	at BaseHTTPServer$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/BaseHTTPServer.py)
            	at BaseHTTPServer$py.handle$8(/usr/local/Cellar/jython/2.7.1/libexec/Lib/BaseHTTPServer.py:352)
            	at BaseHTTPServer$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/BaseHTTPServer.py)
            	at SocketServer$py.__init__$47(/usr/local/Cellar/jython/2.7.1/libexec/Lib/SocketServer.py:659)
            	at SocketServer$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/SocketServer.py)
            	at SocketServer$py.finish_request$13(/usr/local/Cellar/jython/2.7.1/libexec/Lib/SocketServer.py:334)
            	at SocketServer$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/SocketServer.py)
            	at SocketServer$py.process_request$11(/usr/local/Cellar/jython/2.7.1/libexec/Lib/SocketServer.py:322)
            	at SocketServer$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/SocketServer.py)
            	at SocketServer$py._handle_request_noblock$8(/usr/local/Cellar/jython/2.7.1/libexec/Lib/SocketServer.py:298)
            	at SocketServer$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/SocketServer.py)
            	at SocketServer$py.serve_forever$5(/usr/local/Cellar/jython/2.7.1/libexec/Lib/SocketServer.py:241)
            	at SocketServer$py.call_function(/usr/local/Cellar/jython/2.7.1/libexec/Lib/SocketServer.py)
            Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.WebDriverException
            	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
            	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
            	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
            	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
            	... 224 more
            PYTHONPATH:
              /Users/roja/Automation/Jars-For-KTOC/TRBJars1.jar
              /usr/local/Cellar/jython/2.7.1/libexec/Lib/site-packages
              /private/var/folders/dv/nnfc_k29377bv7s34kng7qgh0000gn/T/RobotTempDir8808901746972554502
              /usr/local/Cellar/jython/2.7.1/libexec/Lib
              __classpath__
              __pyclasspath__/
            CLASSPATH:
              ../../../../usr/local/Cellar/jython/2.7.1/libexec/jython.jar
              .
            
            Try --help for usage information.

**Comment by michalanglart** [comment] 2018-12-19 11:46
Basing on this:

> Exception: Importing test library 'com.KTOC.TRB.testautomation.ObjectRepository.pg_SF_HomePage' failed: NoClassDefFoundError: Could not initialize class com.KTOC.TRB.testautomation.ObjectRepository.pg_SF_HomePage
java.lang.NoClassDefFoundError:

Jython does not see this class: `com.KTOC.TRB.testautomation.ObjectRepository.pg_SF_HomePage`. Are you sure you have all required `jars` in `CLASSPATH`? Are you sure that the class file itself is contained in a `jar`?

**Comment by thangaroja** [comment] 2018-12-20 06:16
Yes I do have all respective jar files of my project under  CLASSPATH. Yes the class files are in jar.

**Comment by michalanglart** [comment] 2018-12-20 11:45
I think we need something with which we could reproduce issue on our side. The exception strongly suggest that jython is not able to see some class. It would be great if you could provide some minimal project for which this can be reproduced.

**Comment by michalanglart** [comment] 2018-12-21 11:44
Hi,

I was able to use your jar on my machine without (almost) errors. I've done the following:

- downloaded your jar file
- downloaded selenium-server-standalone-3.141.59.jar
- downloaded client-combined-3.141.59.jar
- downloaded Apache poi-3.7.jar
- in red.xml adding above 3 jars into `CLASSPATH` field
- added your jar via `Add Java library`
- chosen everything in next window

The result is visible down below on screenshot: there are only two errors:
- the `ExcelReader` library (if it is a library) was not created because the constructor requires arguments - this is not supported by RED
- the `KTOCTRBUtils$1` class has no public constructor. But this is private inner class, so I don't think this is a keywords library anyway

![screen1](https://user-images.githubusercontent.com/14932410/50341178-29cd7800-051e-11e9-9aaf-c006a1370fcf.png)
![screen2](https://user-images.githubusercontent.com/14932410/50341183-2cc86880-051e-11e9-9938-5caeb5501466.png)

**Comment by thangaroja** [comment] 2018-12-24 09:40
OOps! Is there any other way to rectify the below constructor issue then? This is quite important for me. The same file was working earlier.
"the ExcelReader library (if it is a library) was not created because the constructor requires arguments - this is not supported by RED"      

Thanks for your workaround. I dont know why 5 of my classes showing in red in my system. Let me recheck.

**Comment by michalanglart** [comment] 2019-02-01 11:19
Closing, please reopen if needed

**Closed by michalanglart** 2019-02-01 11:19 UTC
