### ISSUE TITLE
RED issue - modal dialogs

### ISSUE THREAD

**Issue by scott-au** [nokia/RED#322] opened 2019-07-31 00:22 UTC
Hi,

Using RED plugin (0.8.13), with Git Integration (5.4.0) and PyDev (7.2.1) in Eclipse (4.12.0).

Through Git plugin, started a merge that resulted in conflicts to python libraries

RED popped up multiple modal dialogs – the top one (Progress Information) is waiting for a another one (Multiple problems have occurred) that is waiting for user input, but is not accessible.

![Capture](https://user-images.githubusercontent.com/46589110/62174184-423b2600-b37c-11e9-9b08-85efb911483e.PNG)

Clicking the “Cancel” button on the “generating libdoc” popup doesn’t seem to do anything other than disable itself.

Once it gets into that state, there is no way to progress without killing eclipse.

any one else experienced anything similar ? any suggestions

**Comment by michalanglart** [comment] 2019-07-31 06:36
Hi,

have you tried waiting a bit longer? There should be a timeout on this operation 30 or 60 seconds if I remember correctly.

Do you have the exceptions logged into `<workspace>/metadata/.log` file? Can you show them?

Does this problem still occur after restart and resolving Git conflicts?

**Comment by scott-au** [comment] 2019-08-01 03:08
> have you tried waiting a bit longer? There should be a timeout on this operation 30 or 60 seconds if I remember correctly.

Yes, I’ve tried leaving it alone for about 15 minutes – none of the dialogs change or go away.

> Do you have the exceptions logged into <workspace>/metadata/.log file? Can you show them?

There do not seem to be any related entries in the log. i have attached anyway [eclipse log extracts.log](https://github.com/nokia/RED/files/3454742/eclipse.log.extracts.log)

> Does this problem still occur after restart and resolving Git conflicts?

No – even just restarting eclipse is enough to not get any popups. After restarting eclipse, there are errors, but those do not seem to result in popups.
I can reproduce the issue, using an external editor (Notepad++) instead of the GIT conflicts:
1.	Start with Eclipse open, no errors

2.	In external editor, modify one of the libraries (.py file) – adding an invalid line.
After saving that, popups (“Progress Information” “generating libdoc…”) and (“Problem Occurred”  “Library specification generation problem”) are displayed.
(if 2 libraries are modified at the same time, using editor’s ‘Save All’ function, the second popup title is “Multiple problems have occurred”)
At this stage, the popups can be closed fine (I’m not sure why it needs to be a popup, instead of showing in eclipse problems view)

3.	Back in the external editor, make another change. Another “Progress Information” popup is displayed (modal, preventing user from interacting with other popups). At this point, I can’t find any way to recover without killing eclipse.
Step 3 can be repeated, resulting in more and more modal popups.



Our eclipse project contains robot test suites as well as python libraries (supplying keywords that are used within the tests).

**Comment by michalanglart** [comment] 2019-08-01 06:55
Thank you for reproduction steps - it saves a lot of work! I can confirm this is reproducible regardless the eclipse platform used. We'll have a look what is going on there.

Side note: your `.log` files contains lots of exceptions about RED property testers. This only happens on newest platform (4.12). We are aware of this but haven't looked into that yet. We also haven't checked what is the effect of those exceptions (if any) but if some context menu actions or toolbar buttons does not work or are disabled then this may be the cause. We haven't yet tested RED on eclipse 4.12 because our functional tests are based on RCPTT tool which does not support 4.12 yet.

**Comment by michalanglart** [comment] 2019-10-11 14:41
Fixed in 0.9.0

**Closed by michalanglart** 2019-10-11 14:41 UTC
Labels: bug
