### ISSUE TITLE
Code Assist Doesn't work

### ISSUE THREAD

**Issue by victorka143** [nokia/RED#354] opened 2019-12-03 19:43 UTC
I am having issue with the code assist nothing comes up i checked bunch of videos and solutions how to fix this but i am not able to solve the issue. I added all the alphabet upper and lowercase for trigger but still nothing. I am using Eclipse Version: 2019-09 R (4.13.0)
Build id: 20190917-1200

RED - Robot Editor
Version: 0.9.1

![Error](https://user-images.githubusercontent.com/46330576/70083091-c545e480-15d9-11ea-8ef8-6deb0cd19e24.png)

**Comment by michalanglart** [comment] 2019-12-04 07:19
Hi,

Can you share your project? Was it build? Can you see the libraries in Project Explorer? Can you read their documentations?

**Comment by michalanglart** [comment] 2019-12-17 15:15
Cannot reproduce that without reporter help. Closing

**Closed by michalanglart** 2019-12-17 15:15 UTC
