### ISSUE TITLE
RED doesn't read the PATH correctly on MAC OSX

### ISSUE THREAD

**Issue by pammismail** [nokia/RED#174] opened 2018-01-15 11:55 UTC
Here are the steps to reproduce this

Env: MacOSX and Eclipse Oxygen
1. Download and copy Geckodriver or Chromedriver to usr/local/bin
2. Confirm that both these browser drivers can be launched from terminal(to confirm path is setup correctly)
3. Launch eclipse with RED by double clicking desktop or dock icon and try the following
Set Environment Variable     webdriver.chrome.driver  [Path where chrome driver is copied)
Open Browser    http://www.google.com    gc
4. Observe that the error "'chromedriver' executable needs to be in PATH" as error, despite the PATH is setup correctly. 

Workaround: Launch the eclipse from terminal using "open eclipse.app", this issue is no longer reproducible.

**Comment by michalanglart** [comment] 2018-01-15 12:21
Hi,

have you restarted RED after installing Geckodriver/Chromedriver? 

Normally when some process is starting another one, the environment variables are inherited from parent's process and moreover there is no environment changes monitoring, so overall the child inherits the variables in a state in which they were when parent was started. I think this is a behavior which does not depend upon the system.

If you haven't restarted RED after installing Geckodriver or Chromedriver then python process with tests was started with PATH variable in a state in which it was when RED was started. Quiting and launching again is fixing the problem because then RED starts with PATH variable with its new value.

**Comment by pammismail** [comment] 2018-01-15 12:44
Yes, I've restarted several times and that doesn't solve the problem.

**Comment by michalanglart** [comment] 2018-01-15 13:22
Restarted by using `File -> Restart` menu or by exiting RED and launching it again?

**Comment by modrz** [comment] 2018-01-16 07:16
If RED is started from terminal you should also restart terminal after updating environment variables.

**Comment by pammismail** [comment] 2018-01-16 08:26
Starting or restarting from Terminal->open eclipse.app is only working but not my File->restart

**Comment by michalanglart** [comment] 2018-01-16 08:40
Yes, `File->Restart` will not work.

The inner mechanics of eclipse and hence RED is that once you click the RED executable file, the launching process starts. It loads some files, performs couple of operations and then it starts another process: Java Virtual Machine, which loads all the jars and executes the java code of eclipse/RED.

The `File -> Restart` option only restarts Java Virtual Machine but it does not quit the launcher process. 

As a result: 
- you launch RED executable and this new process will have all the environment variables copied with their values
- it launches Java process which again copies the values of env variables to this new process
- you're changing the environment variable but it does not affect currently running processes
- you're clicking `File->Restart` which quits Java process and starts new one again but without quiting the parent process;
- newly launched Java process have env variables copied from parent process but the changes are not there, so it will still see old values

In order to see env variables changed in RED you need to restart it with all the parent processes, so you need to quit it and launch again or if it is started from terminal also the terminal needs to be restarted to see updated values as @modrz pointed out above.

**Comment by KrzysztofJozefowicz** [comment] 2018-02-06 14:06
released in 0.8.3

**Closed by KrzysztofJozefowicz** 2018-02-06 14:06 UTC

**Comment by sebastianciupinski** [comment] 2018-10-11 08:19
I think problem still exists

**Comment by luhuangAccedo** [comment] 2018-11-15 07:42
I solved this issue on my Mac High Sierra with RED 0.8.8 by following steps:
1. Home brew install chromedriver latest
2. Check availability /usr/local/bin/chromedriver
3. Check "/usr/local/bin" under PATH
4. In terminal, >open /Applications/RED.app

Any other ways to launch RED will still reproduce the issue under same environment.

**Comment by AbigailPiner** [comment] 2020-12-13 03:39
> Here are the steps to reproduce this
> 
> Env: MacOSX and Eclipse Oxygen
> 
> 1. Download and copy Geckodriver or Chromedriver to usr/local/bin
> 2. Confirm that both these browser drivers can be launched from terminal(to confirm path is setup correctly)
> 3. Launch eclipse with RED by double clicking desktop or dock icon and try the following
>    Set Environment Variable     webdriver.chrome.driver  [Path where chrome driver is copied)
>    Open Browser    http://www.google.com    gc
> 4. Observe that the error "'chromedriver' executable needs to be in PATH" as error, despite the PATH is setup correctly.
> 
> Workaround: Launch the eclipse from terminal using "open eclipse.app", this issue is no longer reproducible.

I know this is years later... but thank you so much for this! I have spent HOURS trying to solve this problem. Done every possible article and forum suggestion I have found. And finally, I found your post with the workaround to open direct from Terminal. I don't know why... but it worked! If I open via my applications area, it's a no-go. 

THANK YOU
